### ISSUE TITLE
Jupyter: Iteration Plan for June 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#10430]
This plan captures our work in **June**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/151843). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- :repeat: Maintain empty list of issues labeled as an [important Golden Scenario or significant regression](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant%2Cnotebook-regression+-label%3Ainfo-needed) issue. @greazer **team**
- [x] Ipywidget regression [vscode-jupyter#9821](https://github.com/microsoft/vscode-jupyter/issues/9821) @donjaymanne

### General 
- [x] Shell based kernel support [vscode-jupyter#9682](https://github.com/microsoft/vscode-jupyter/issues/9682) @donjayamanne
- [x] Explore pasting images into markdown cells [vscode-jupyter#5321](https://github.com/microsoft/vscode-jupyter/issues/5321), [vscode#119961](https://github.com/microsoft/vscode/issues/119961) @yoyokrazy, @amunger, @mjbvz
- [x] Explore support for Apple Silicon and other platforms [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206) @donjayamanne
- [x] Notebook Debugging Fixes found while enabling IW debugging for web. [vscode-jupyter#10106](https://github.com/microsoft/vscode-jupyter/issues/10106) @donjayamanne
- [ ] :red_circle: :muscle: Variable Explorer low hanging fruit cleanup @sadasant

### Web-enablement
- [ ] :runner: Cleanup support for remote Jupyter server URI's for web and desktop - [main issue vscode-jupyter#10435](https://github.com/microsoft/vscode-jupyter/issues/10435) (related [vscode-jupyter#9574](https://github.com/microsoft/vscode-jupyter/issues/9574), [vscode-jupyter#10363](https://github.com/microsoft/vscode-jupyter/issues/10363), [vscode-jupyter#10312](https://github.com/microsoft/vscode-jupyter/issues/10312), [vscode-jupyter#10191](https://github.com/microsoft/vscode-jupyter/issues/10191)) @rchiodo 
- [ ] :runner: Dataframe viewer [vscode-jupyter#9665](https://github.com/microsoft/vscode-jupyter/issues/9665), [vscode-jupyter#10200](https://github.com/microsoft/vscode-jupyter/issues/10200)
- [ ] :runner: Plot viewer [vscode-jupyter#10405](https://github.com/microsoft/vscode-jupyter/issues/10405) @sadasant
- [x] Clean up support for ipywidgets in remote jupyter scenarios. @donjayamanne [vscode-jupyter#10434](https://github.com/microsoft/vscode-jupyter/issues/10434)
- [x] IW issues [vscode-jupyter#10282](https://github.com/microsoft/vscode-jupyter/issues/10282), [vscode-jupyter#10291](https://github.com/microsoft/vscode-jupyter/issues/10291) @amunger
- [x] Error Links [vscode-jupyter#10287](https://github.com/microsoft/vscode-jupyter/issues/10287) @rchiodo

### Getting started
- [x] With Core and Python, identify and address Low hanging fruit to improve existing workflows for the clean machine experience. [board](https://github.com/orgs/microsoft/projects/359/views/1), https://github.com/microsoft/vscode-jupyter/issues/10513 @IanMatthewHuff
    - [ ] :runner: Fix ipykernel prompt text [vscode-jupyter#10295](https://github.com/microsoft/vscode-jupyter/issues/10295) @IanMatthewHuff

### Engineering
- [x] Localize using vscode-loc [vscode-jupyter#9676](https://github.com/microsoft/vscode-jupyter/issues/9676) @sadasant
- [ ] :runner: :hand: Migrate off of the `vscode.proposed.notebookDeprecated` [vscode-jupyter#9629](https://github.com/microsoft/vscode-jupyter/issues/9629) @sadasant
- [x] Improve overall structure of the code base [vscode-jupyter#10152](https://github.com/microsoft/vscode-jupyter/issues/10152) @rebornix
    - [ ] Improve build time [vscode-jupyter#10399](https://github.com/microsoft/vscode-jupyter/issues/10399) @rebornix
    - [x] Reduce bundle size of the Jupyter extension [vscode-jupyter#10307](https://github.com/microsoft/vscode-jupyter/issues/10307) @rebornix
