### ISSUE TITLE
Jupyter: Iteration Plan for July 2022 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#10749]
This plan captures our work in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/154652). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- :repeat: Maintain empty list of issues labeled as an [important Golden Scenario or significant regression](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant%2Cnotebook-regression+-label%3Ainfo-needed) issue. @greazer **team**

### General 
- [ ] :runner: Paste Images into Markdown cells [vscode-jupyter#5321](https://github.com/microsoft/vscode-jupyter/issues/5321), [vscode#119961](https://github.com/microsoft/vscode/issues/119961) @yoyokrazy, @amunger, @mjbvz
- [x] Copy images from cell outputs to clipboard [vscode#129880](https://github.com/microsoft/vscode/issues/129880) @amunger
- [x] Cleanup handling of environment variables when starting kernels [vscode-jupyter#10359](https://github.com/microsoft/vscode-jupyter/issues/10359) @donjayamanne
- [x] Interactive Window hot exit [vscode-jupyter#10733](https://github.com/microsoft/vscode-jupyter/issues/10733) @rebornix
- [ ] :runner: Drive scenarios and behavior for IW Input Box Intellisense plan across Python, Pylance, LSP, Jupyter [vscode-jupyter#10630](https://github.com/microsoft/vscode-jupyter/issues/10630) [vscode#151994](https://github.com/microsoft/vscode/issues/151994) @rchiodo @debonte 
- [ ] :muscle: :red_circle: Submit bug fix for ZMQ to allow us to build and ship without regressions. Required for [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206) @rchiodo

### Web-enablement
- [x] Polish support for remote Jupyter server URI's for web and desktop [vscode-jupyter#10672](https://github.com/microsoft/vscode-jupyter/issues/10672) [vscode-jupyter#10675](https://github.com/microsoft/vscode-jupyter/issues/10675) [vscode-jupyter#10782](https://github.com/microsoft/vscode-jupyter/issues/10782) @rchiodo 
- [x] Dataframe viewer [vscode-jupyter#9665](https://github.com/microsoft/vscode-jupyter/issues/9665), [vscode-jupyter#10200](https://github.com/microsoft/vscode-jupyter/issues/10200) @sadasant
- [x] Plot viewer [vscode-jupyter#10405](https://github.com/microsoft/vscode-jupyter/issues/10405) @sadasant
- [x] Jupyter can't be activated on Safari [vscode-jupyter#10621](https://github.com/microsoft/vscode-jupyter/issues/10621) @donjayamanne
- [ ] :muscle: Remote files and synchronization story [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366), [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975) @rchiodo
- [ ] :runner: :muscle: intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976) @rchiodo, **pylance team**, **python team**

### Getting started
- [x] Clean up messaging and notifications for the Jupyter / Python first run scenarios @IanMatthewHuff
  - [x] [vscode-jupyter#6886](https://github.com/microsoft/vscode-jupyter/issues/6886)
  - [x] [vscode-jupyter#7907](https://github.com/microsoft/vscode-jupyter/issues/7907)
  - [x] [vscode-jupyter#10615](https://github.com/microsoft/vscode-jupyter/issues/10615)
  - [x] [vscode-jupyter#10658](https://github.com/microsoft/vscode-jupyter/issues/10658)
  - [x] [vscode-jupyter#10697](https://github.com/microsoft/vscode-jupyter/issues/10697)
  - [x] [vscode-jupyter#10696](https://github.com/microsoft/vscode-jupyter/issues/10696)
  - [x] [vscode-jupyter#10793](https://github.com/microsoft/vscode-jupyter/issues/10693)

### Engineering
- [ ] :runner: Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix, @donjayamanne
- [x] Further clarify and implement changes to improve our CI process [vscode-jupyter#10634](https://github.com/microsoft/vscode-jupyter/issues/10634)  mainly in regard to tests. @amunger, @greazer **team**
- [ ] :runner: Improve build time [vscode-jupyter#10399](https://github.com/microsoft/vscode-jupyter/issues/10399) @rebornix, @rchiodo
- [x] Resolve notebook output id metadata with API team [vscode-jupyter#9629](https://github.com/microsoft/vscode-jupyter/issues/9629) @sadasant
- [ ] :muscle: :red_circle: Debugging/debugger architecture review and polish @sadasant

-----

### Deferred
- [ ] Investigate a method to create or suggest a virtual environment with ipykernel + needed packages for a given notebook [vscode-jupyter#9640](https://github.com/microsoft/vscode-jupyter/issues/9640) @IanMatthewHuff
