### ISSUE TITLE
Jupyter: Iteration Plan for August 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11064]
This plan captures our work in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/157454). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [ ] :runner: Review/rethink Server/Kernel picker [vscode-jupyter#11077](https://github.com/microsoft/vscode-jupyter/issues/11077) @minsa110 @misolori @IanMatthewHuff

### General
- [ ] :runner: Support pasting images into Markdown cells [vscode-jupyter#5321](https://github.com/microsoft/vscode-jupyter/issues/5321), [vscode#119961](https://github.com/microsoft/vscode/issues/119961) @yoyokrazy @mjbvz
- [x] Adopt new cell context key pattern [vscode-jupyter#10595](https://github.com/microsoft/vscode-jupyter/issues/10595) @roblourens
- [x] Investigate creating a virtual environment for a notebook/workspace [vscode-jupyter#9640](https://github.com/microsoft/vscode-jupyter/issues/9640) @IanMatthewHuff @minsa110
- [x] Ensure cell is not stuck in execution when server connection goes down @DonJayamanne [vscode-jupyter#10568](https://github.com/microsoft/vscode-jupyter/issues/10568)
- [x] Improve reliability of tests [vscode-jupyter#10634](https://github.com/microsoft/vscode-jupyter/issues/10634) @amunger

### Kernels
- [x] Ensure correct process cleanup when a notebook closes @DonJayamanne [vscode-jupyter#11018](https://github.com/microsoft/vscode-jupyter/issues/11018)
- [x] Improved kernel error messages for users @DonJayamanne [vscode-jupyter#1110](https://github.com/microsoft/vscode-jupyter/issues/11092)
- [x] Investigate elimination of backup kernels and interrupt handlers processes @DonJayamanne [vscode-jupyter#9909](https://github.com/microsoft/vscode-jupyter/issues/9909)
- [x] Allow connecting to Jupyter Servers that require authentication @IanMatthewHuff [vscode-jupyter#10300](https://github.com/microsoft/vscode-jupyter/issues/10300)
- [ ] :runner: Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix @donjayamanne

### Debugging
- [ ] :runner: Restart Run-by-Line debugging session when stopped in a python file [vscode-jupyter#7611](https://github.com/microsoft/vscode-jupyter/issues/7611) @roblourens
- [ ] :runner: Improve reliability of Run-by-Line [vscode-jupyter#11006](https://github.com/microsoft/vscode-jupyter/issues/11006) @roblourens
- [ ] :muscle: Enable `ipykernel 6` debugging in the interactive window [query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+forceIPyKernelDebugger) @roblourens
- [ ] :muscle: Debugging/debugger architecture review and polish [vscode-jupyter#11108](https://github.com/microsoft/vscode-jupyter/issues/11108) @roblourens @rebornix

### Interactive Window
- [x] Ensure correct execution order in the Interactive Window [vscode-jupyter#10671](https://github.com/microsoft/vscode-jupyter/issues/10671) @amunger
- [ ] :runner: Improve keyboard navigation in the Interactive Window [vscode#148820](https://github.com/microsoft/vscode/issues/148820) @amunger

### Deferred
- [ ] Show in editor progress when connecting to a kernel (not just the notification) @rebornix @DonJayamanne [vscode-jupyter#11161](https://github.com/microsoft/vscode-jupyter/issues/11161)
- [ ] Ensure Plotly widgets are rendered when opening a notebook @DonJayamanne [vscode-jupyter#6404](https://github.com/microsoft/vscode-jupyter/issues/6404)
- [ ] Enable test run history [vscode-jupyter#9218](https://github.com/microsoft/vscode-jupyter/issues/9218) @amunger
- [ ] Improve build time [vscode-jupyter#10399](https://github.com/microsoft/vscode-jupyter/issues/10399) @rebornix @rchiodo
- [ ] Drive scenarios and behavior for IW Input Box Intellisense plan across Python, Pylance, LSP, Jupyter [vscode-jupyter#10630](https://github.com/microsoft/vscode-jupyter/issues/10630) [vscode#151994](https://github.com/microsoft/vscode/issues/151994) @rchiodo @debonte
- [ ] Submit bug fix for ZMQ to allow us to build and ship without regressions. Required for [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206) @rchiodo
- [ ] Remote files and synchronization story [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366), [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975) @rchiodo
- [ ] Intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976) @rchiodo **pylance team** **python team**
