### ISSUE TITLE
Address kernel startup and connection problems (okr)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1122]
* Interpreter is known to be conda, and no activation commands were found
* Interpreter is known to be conda, and activated environment variables were not generated
* Interpreter is known to be conda, and generating env variables failed
* [x] microsoft/vscode-jupyter#6739
* [x] microsoft/vscode-jupyter#6425
* [ ] microsoft/vscode-jupyter#6414
* [x] microsoft/vscode-jupyter#5061
* [x] microsoft/vscode-jupyter#1129
* [x] microsoft/vscode-jupyter#4593
* [ ] microsoft/vscode-jupyter#450
* [x] microsoft/vscode-jupyter#1125
* [x] microsoft/vscode-jupyter#1131
* [x] microsoft/vscode-jupyter#1124
* [x] microsoft/vscode-jupyter#1128
* [x] microsoft/vscode-jupyter#1253
* [x] microsoft/vscode-jupyter#1257
* [x] microsoft/vscode-jupyter#1269
* [x] microsoft/vscode-jupyter#1698
* [x] microsoft/vscode-jupyter#1644
* [x] microsoft/vscode-jupyter#1591
* [x] microsoft/vscode-jupyter#421
* [x] microsoft/vscode-jupyter#1440
* [x] microsoft/vscode-jupyter#617
* [x] microsoft/vscode-jupyter#1184
* [x] microsoft/vscode-jupyter#4244
* [x] microsoft/vscode-jupyter#5211
* [x] microsoft/vscode-jupyter#5293
* [x] microsoft/vscode-jupyter#5394
* [x] microsoft/vscode-jupyter#5459
* [x] microsoft/vscode-jupyter#5494
* [x] microsoft/vscode-jupyter#5736
* [ ] microsoft/vscode-jupyter#5897
* [ ] microsoft/vscode-jupyter#5998
* [x] microsoft/vscode-jupyter#6087
* [ ] microsoft/vscode-jupyter-internal#40
* [ ] microsoft/vscode-jupyter-internal#77
* [ ] microsoft/vscode-jupyter-internal#79
* [ ] microsoft/vscode-jupyter-internal#89
* [ ] microsoft/vscode-jupyter-internal#61
* [ ] microsoft/vscode-jupyter#5314
* [x] microsoft/vscode-jupyter#5650

**Comment by DonJayamanne** [comment]
Closing this issue, as this is old and outdated now.
