### ISSUE TITLE
Jupyter: Iteration Plan for September 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11286]
This plan captures our work in **September**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/160046). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Support pasting images into Markdown cells [vscode-jupyter#5321](https://github.com/microsoft/vscode-jupyter/issues/5321) @rebornix @mjbvz @amunger
- [x] Investigate a notebook/cell metadata editor [vscode-jupyter#1182](https://github.com/microsoft/vscode-jupyter/issues/1182) @rebornix
- [x] Provide support for tagging cells using cell metadata [vscode-jupyter#1121](https://github.com/microsoft/vscode-jupyter/issues/1121) @rebornix

### Outputs
- [ ] :runner: Fix crashes caused by large outputs [vscode-jupyter#11031](https://github.com/microsoft/vscode-jupyter/issues/11031) @DonJayamanne @roblourens @rebornix
- [ ] :runner: Investigate how to render stored Plotly, Vega outputs when opening a notebook [vscode-jupyter#11218](https://github.com/microsoft/vscode-jupyter/issues/11218) @DonJayamanne @mjbvz
- [ ] :runner: Render stored Matplotlib png output as a fallback when opening a notebook [vscode-jupyter#8635](https://github.com/microsoft/vscode-jupyter/issues/8635) @DonJayamanne @mjbvz
- [x] Explore support for iPyWidgets 8 [vscode-jupyter#11217](https://github.com/microsoft/vscode-jupyter/issues/11217) @DonJayamanne

### Kernels
- [ ] :runner: Review/rethink Server/Kernel picker [vscode-jupyter#11077](https://github.com/microsoft/vscode-jupyter/issues/11077) @IanMatthewHuff @minsa110
- [x] Use "Learn more..." buttons to guide users to more information [vscode-jupyter#11285](https://github.com/microsoft/vscode-jupyter/issues/11285) @IanMatthewHuff
- [ ] :runner: Adopt the new Python Extension API for python environments [vscode-jupyter#7583](https://github.com/microsoft/vscode-jupyter/issues/7583) @DonJayamanne

### Debugging
- [x] Improve reliability of Run-by-Line [vscode-jupyter#11006](https://github.com/microsoft/vscode-jupyter/issues/11006) @roblourens
- [x] Restart Run-by-Line debugging session when stopped in a python file [vscode-jupyter#7611](https://github.com/microsoft/vscode-jupyter/issues/7611) @roblourens
- [ ] :runner: Remove notifications about why library code was not stepped into [microsoft/debugpy#1019](https://github.com/microsoft/debugpy/issues/1019) @roblourens
- [x] Test debugging when connected to a Jupyter Server [microsoft/vscode-jupyter#11406](https://github.com/microsoft/vscode-jupyter/issues/11406) @roblourens

### Interactive Window
- [x] Improve keyboard navigation in the Interactive Window [vscode#148820](https://github.com/microsoft/vscode/issues/148820) @amunger
- [x] Stabilize the Interactive Window https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aopen+label%3Ainteractive-window+label%3Abug+milestone%3A%22September+2022%22 @amunger
- [x] Support folding of cells in python files [vscode-jupyter#1527](https://github.com/microsoft/vscode-jupyter/issues/1527) @amunger

### Engineering
- [x] Enable queries on CI test run history [vscode-jupyter#9218](https://github.com/microsoft/vscode-jupyter/issues/9218) @amunger

### Deferred
- [ ] Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix @DonJayamanne
- [ ] Enable `ipykernel 6` debugging in the interactive window [query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+forceIPyKernelDebugger) @roblourens
- [ ] Debugging/debugger architecture review and polish [vscode-jupyter#11108](https://github.com/microsoft/vscode-jupyter/issues/11108) @roblourens
- [ ] Show in editor progress when connecting to a kernel (not just the notification) @rebornix @DonJayamanne [vscode-jupyter#11161](https://github.com/microsoft/vscode-jupyter/issues/11161)
- [ ] Drive scenarios and behavior for IW Input Box Intellisense plan across Python, Pylance, LSP, Jupyter [vscode-jupyter#10630](https://github.com/microsoft/vscode-jupyter/issues/10630) [vscode#151994](https://github.com/microsoft/vscode/issues/151994)
- [ ] Remote files and synchronization story [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366), [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975)
- [ ] Intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976)
