### ISSUE TITLE
Jupyter: Iteration Plan for October 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11581]
This plan captures our work in **October**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/163069). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Improve performance for providing `.py` code lenses [vscode-jupyter#11433](https://github.com/microsoft/vscode-jupyter/issues/11433) @amunger

### Outputs
- [x] Fix crashes caused by large outputs [vscode-jupyter#11031](https://github.com/microsoft/vscode-jupyter/issues/11031) @DonJayamanne @roblourens @rebornix
- [x] Investigate how to render stored Plotly, Vega outputs when opening a notebook [vscode-jupyter#11218](https://github.com/microsoft/vscode-jupyter/issues/11218) @DonJayamanne @mjbvz
- [ ] :runner: Render stored Matplotlib png output as a fallback when opening a notebook [vscode-jupyter#8635](https://github.com/microsoft/vscode-jupyter/issues/8635) @DonJayamanne @mjbvz

### Kernels
- [x] Adopt the new Python Extension API for python environments [vscode-jupyter#7583](https://github.com/microsoft/vscode-jupyter/issues/7583) @DonJayamanne
- [x] Ship prototype of per document kernel source selection under an experimental flag [vscode-jupyter#11576](https://github.com/microsoft/vscode-jupyter/issues/11576) @IanMatthewHuff
- [ ] :muscle: Expand insiders kernel picker options to show an MRU section and an active sessions section [vscode-jupyter#11577](https://github.com/microsoft/vscode-jupyter/issues/11577) @IanMatthewHuff

### Debugging
- [x] Support disabling “justMyCode” for jupyter debugging [vscode-jupyter#8146](https://github.com/microsoft/vscode-jupyter/issues/8146) @roblourens
- [x] Implement Restart for Jupyter debugging [vscode-jupyter#7670](https://github.com/microsoft/vscode-jupyter/issues/7670) @roblourens

### Interactive Window
- [x] Add find widget to Interactive Window [vscode#130587](https://github.com/microsoft/vscode/issues/130587) @amunger
- [ ] :runner: Clean up Interactive Window creation/restore [vscode-jupyter#10808](https://github.com/microsoft/vscode-jupyter/issues/10808) @amunger

-----
### Deferred
- [ ] Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix @DonJayamanne
- [ ] Debugging/debugger architecture review and polish [vscode-jupyter#11108](https://github.com/microsoft/vscode-jupyter/issues/11108) @roblourens
- [ ] Enable `ipykernel 6` debugging in the interactive window [query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+forceIPyKernelDebugger) @roblourens
- [ ] Show in editor progress when connecting to a kernel (not just the notification) [vscode-jupyter#11161](https://github.com/microsoft/vscode-jupyter/issues/11161) @rebornix @DonJayamanne
- [ ] Remote files and synchronization story [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366), [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975) @DonJayamanne
- [ ] Intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976) @IanMatthewHuff
