### ISSUE TITLE
Jupyter: Iteration Plan for November 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#11922]
This plan captures our work in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/165643). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Improve performance for providing `.py` code lenses [vscode-jupyter#11433](https://github.com/microsoft/vscode-jupyter/issues/11433) @amunger
- [x] Explore improving variables viewer performance [vscode-jupyter#11745](https://github.com/microsoft/vscode-jupyter/issues/11745) @roblourens
- [x] Ensure the variable viewer is never automatically revealed [vscode-jupyter#11986](https://github.com/microsoft/vscode-jupyter/issues/11986) @roblourens
- [x] Support pasting of images by default (not experimental anymore) [vscode-jupyter#11987](https://github.com/microsoft/vscode-jupyter/issues/11987) @mjbvz

### Outputs
- [x] Fix crashes caused by large outputs [vscode-jupyter#11031](https://github.com/microsoft/vscode-jupyter/issues/11031) @DonJayamanne @roblourens @rebornix
- [ ] :runner: On notebook restore, fallback if an `ipywidget` needs an active kernel connection [vscode-jupyter#8635](https://github.com/microsoft/vscode-jupyter/issues/8635) @DonJayamanne @mjbvz

### Kernels
- [x] Adopt the new Python Extension API for python environments [vscode-jupyter#7583](https://github.com/microsoft/vscode-jupyter/issues/7583) @DonJayamanne
- [x] Ship prototype of per document kernel source selection under an experimental flag [vscode-jupyter#11576](https://github.com/microsoft/vscode-jupyter/issues/11576) @IanMatthewHuff
- [ ] :runner: Continued polish of the Kernel Picker [vscode-jupyter#11904](https://github.com/microsoft/vscode-jupyter/issues/11904) @rebornix @DonJayamanne
- [x] Show progress on kernel status item when connecting to a kernel (not just the notification) [vscode-jupyter#11161](https://github.com/microsoft/vscode-jupyter/issues/11161) @rebornix @DonJayamanne

### Debugging
- [x] Support disabling "justMyCode" for jupyter debugging [vscode-jupyter#8146](https://github.com/microsoft/vscode-jupyter/issues/8146) @roblourens
- [x] Implement Restart for Jupyter debugging [vscode-jupyter#7670](https://github.com/microsoft/vscode-jupyter/issues/7670) @roblourens
- [ ] :runner: Allow disabling "justMyCode" in Interactive Window with `ipykernel` debugging [vscode-jupyter#11777](https://github.com/microsoft/vscode-jupyter/issues/11777) @roblourens
- [ ] :runner: Investigate `debugpy` hangs in Jupyter debugging [debugpy#1051](https://github.com/microsoft/debugpy/issues/1051) @roblourens

### Interactive Window
- [x] Add find widget to Interactive Window [vscode#130587](https://github.com/microsoft/vscode/issues/130587) @amunger
- [ ] :runner: Clean up Interactive Window creation/restore [vscode-jupyter#10808](https://github.com/microsoft/vscode-jupyter/issues/10808) @amunger

### Engineering
- [x] Adopt the npm ADO pipeline for https://github/microsoft/vscode-jupyter-ipywidgets @DonJayamanne

-----
### Deferred
- [ ] :muscle: Support `ipywidget 8` @DonJayamanne [vscode-jupyter#8552](https://github.com/microsoft/vscode-jupyter/issues/8552)
- [ ] Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix @DonJayamanne
- [ ] Debugging/debugger architecture review and polish [vscode-jupyter#11108](https://github.com/microsoft/vscode-jupyter/issues/11108) @roblourens
- [ ] Enable `ipykernel 6` debugging in the interactive window [query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+forceIPyKernelDebugger) @roblourens
- [ ] Remote files and synchronization story [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366), [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975) @DonJayamanne
- [ ] Intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976) @IanMatthewHuff
