### ISSUE TITLE
Native Notebook Kernel Issues

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1229]
* [x] Support non-raw (starting Jupyter) kernels for VSC Native Notebooks microsoft/vscode-python#13253
* [ ] Support connecting to remote kernels in VSC Notebooks microsoft/vscode-python#13250 
* [x] Support saving the remote kernel for reuse on next open microsoft/vscode-python#13249
* [x] Selecting a kernel does not prompt to install missing dependencies microsoft/vscode-python#13266
* [x] Support non-python kernels (needs to be tested)
* [x] Re-selecting the same kernel results in updates to notebook and switching of kernel microsoft/vscode-jupyter#787
* [x] Once raw notebook kernel is in broken state there's no way to recover unless you restart VS COde¸#13275
* [x] Interrupting kernels does not work in VSC Native Notebooks microsoft/vscode-jupyter#780
* [x] Raw kernel interrutp does not seem to work at all on Mac microsoft/vscode-jupyter#682

**Comment by DonJayamanne** [comment]
All issues have been resolved & we have a separate issue to track remote #254
