### ISSUE TITLE
Native Notebook / Webview parity checklist

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#1231]
This epic represents the work we need to reach parity with our current notebook and interactive window behavior such that we can turn it on for everyone.

### VSCode Issues in order of priority
* [x] Preferred kernel is not respected by VS Code (mentioned on teams) https://github.com/microsoft/vscode-python/issues/14155
* [x] Latex in Markdown https://github.com/microsoft/vscode-python/issues/13161
* [x] Output not displayed at times (mentioned on teams)
* [x] Triggering changes to notebook causes outputs to not get displayed (mentioned on teams)
* [x] Table of contents https://github.com/microsoft/vscode/issues/98173
* [x] Trusting Notebooks vs Trust Workspaces?
* [x] CellStreamOutput does not work well, currently using Rich Output. Is this the preferred way. (mentioned on teams). Seems wrong to use it.
* [x] Undo keybinding not working as expected https://github.com/microsoft/vscode-python/issues/13316
* [x] Copying cells copies the execution count as well https://github.com/microsoft/vscode-python/issues/12819
* [x] Readonly notebooks allow editing of cells (notebooks not trusted are readonly) https://github.com/microsoft/vscode/issues/104176
* [x] Renderer needs to communicate with extension (we can do this, but how can renderer & extension identify the output uniquely. The outputId is not available in a notebook cell output). https://github.com/microsoft/vscode/issues/103864#issuecomment-675132563
* [x] Clearing cell should clear execution, execution times order https://github.com/microsoft/vscode-python/issues/13159, 
	* Preferably provide an event so we know user has cleared a cell.
	* We also need to be able to mark document as dirty.
	* https://github.com/microsoft/vscode/issues/103713
* Clearing cells should trigger a change in the notebook https://github.com/microsoft/vscode/issues/103713
* [x] Kernel story (there were issues with current design and we were waiting for staff to return from holidays)
* [x] VIM Keyboard, unable to escape https://github.com/microsoft/vscode-python/issues/12822
* [x] Intellisense for cells (LS needs a single document or we need a change in LSP)
* [x] Run all below/all above https://github.com/microsoft/vscode/issues/98282
* [ ] Images with relative paths in markdown/html output for untitled files https://github.com/microsoft/vscode/issues/99139
* [x] Sending messages to Notebook Renderers does not work (is this a known issue?)
* [x] Can we have a third cell type `raw` (markdown, code & raw) https://github.com/microsoft/vscode-python/issues/7952
	* Can extension contribute to types of cells?
	* Possibly a good time to look at super cells as well (so we have code, markdown, raw, super, etc), stuff that extensions contribute
* [x] CI Tests fail every now and then https://dev.azure.com/ms/vscode-python/_build/results?buildId=97479&view=logs&j=97f6daac-606a-5b3e-ec4c-7c15dc363dc1&t=377cca0f-8a41-5fa6-e993-ec4a6587bd59
* [x] Callbacks from rendered HTML to extension not working https://github.com/microsoft/vscode/issues/98353
* [x] Renderers do not render output if custom renderer output is not the default (i.e. if user has to select the custom renderer, then it doesnt work)
* [x] Interrupt kernel (support multiple cancellations) https://github.com/microsoft/vscode/issues/99203
* [x] Links in Markdown and Output https://github.com/microsoft/vscode/issues/98100
* [x] Keyboard shortcuts for commands not working https://github.com/microsoft/vscode/issues/104860

### GA Check list
* [x] Variable viewer
* [x] Plot viewer
* [x] Ipywidgets (Don WIP)
* [x] Language features
    * [x] Autocomplete, Hover, Signature help
* [x] Kernels  
    * [x] Preferred kernel is not working
    * [x] Selection of local kernel
    * [x] Selection of remote kernels
    * [x] Kernels (Other languages)
* [x] Gather
* [x] Remote Jupyter
* [ ] Jupyter activity bar
* [x] Run by line
* [ ] Raw cells?
* [ ] Extended Language Features
    * [ ] Formatting
    * [ ] Linting
    * [ ] Refactoring
    * [ ] Sort imports
    * [ ] Goto def
* [ ] Live share (needs to be tested with widgets, plots, run by line, gather)
* [ ] Use new NB for start page (this must be used when users are in experiment) - hopefully nothing to do here.
* [ ] Refactor to remove old code (transition to new stuff), there's an issue for this
* [ ] Run all below/all above (command, do we need icons?)
* [ ] Update nterat in renderers
* [ ] Renderers extension
* [ ] Using renderer extension scripts in interactive window
* [x] White backgrounds for vega plots
* [x] White backgrounds for SVGs (e.g. axes in `plt.plot` aren't visible in dark mode)
* [x] Verify that renaming notebooks works
* [x] Trusted notebooks
* [x] Export (pdf/html) - should be the easiest from this entire list
* [ ] Full blown debugger

<details>
<summary>Breakdown</summary>

### IPyWidgets (breakdown)
* [ ] Renderers for IPyWidgets
	* **Prototype available**
	* [ ] Copy stuff from `container.tsx` and hook up comms
	* [ ] Create index.tsx purely widgets
* [ ] Extension Listeners
	* [ ] IPyWidgetHandler
	* [ ] IPyWidgetScriptSource
* [ ] Refactor our UI tests
	* Launch HTML page act like NB that only displays output

### Variable Explorer (breakdown)
* [ ] Jupyter in Activity Bar
* [ ] Varialbles
	* Variables in a new panel (in Jupyter sidebar panel)
	* Use treeview.
* [ ] Kernels
* [ ] Metadata

### Miscellaneous
* [x] (3) Kernel selection & Updating metadata
	* Move or copy (little code), but needs to be done in right place
	* Automatically & manually selecting a kernel & updating metadata
	* Move or copy code, but needs to be done in right place
	* Preferably move (to ensure we do things right, as this has a lot of business rules)
* [ ] Gather extension
* [ ] Trusted notebooks

### Notebook handling
* [ ] Standardize names for notebook objects (we will have 4)
	* nbformat.xx for Jupyter Cells and Output
	* INotebookModel & ICell for out models
	* NotebookData & NotebookCellData for VSCode model
	* NotebookDocument & NotebookCell for VS Code models
	* [ ] Refactor to use new naming convention (to discuss if this is confusing). With the new VSC API, this is very confusing.

### Language features
* [ ] Hover provider (new work done as part of Run by line)

</details>

**Comment by greazer** [comment]
Just about all of this has been accounted for. If not, we'll find out through further feedback.

**Comment by Jimimaku** [comment]
> Dieses Epos repräsentiert die Arbeit, die wir brauchen, um Parität mit unserem aktuellen Notizbuch- und interaktiven Fensterverhalten zu erreichen, so dass wir es für alle einschalten können.
> 
> ### VSCode-Probleme in der Reihenfolge ihrer Priorität
> * [x]  Bevorzugter Kernel wird von VS Code (in Teams erwähnt) https://github.com/microsoft/vscode-python/issues/14155 nicht respektiert
> * [x]  Latex im [Markdown-https://github.com/microsoft/vscode-python/issues/13161](https://github.com/microsoft/vscode-python/issues/13161)
> * [x]  Ausgabe wird manchmal nicht angezeigt (in Teams erwähnt)
> * [x]  Das Auslösen von Änderungen am Notizbuch führt dazu, dass Ausgaben nicht angezeigt werden (in Teams erwähnt)
> * [x]  Inhaltsverzeichnis [Unterstützung der Gliederung mit Notebooks vscode#98173](https://github.com/microsoft/vscode/issues/98173)
> * [x]  Vertrauenswürdige Notebooks im Vergleich zu vertrauenswürdigen Arbeitsbereichen?
> * [x]  CellStreamOutput funktioniert nicht gut und verwendet derzeit Rich Output. Ist dies der bevorzugte Weg? (erwähnt auf Teams). Scheint falsch zu sein, es zu benutzen.
> * [x]  Keybinding rückgängig machen funktioniert nicht wie erwartet https://github.com/microsoft/vscode-python/issues/13316
> * [x]  Durch das Kopieren von Zellen wird auch die Ausführungsanzahl [kopiert https://github.com/microsoft/vscode-python/issues/12819](https://github.com/microsoft/vscode-python/issues/12819)
> * [x]  Schreibgeschützte Notizbücher ermöglichen das Bearbeiten von Zellen (nicht vertrauenswürdige Notizbücher sind schreibgeschützt) [Schreibgeschützte Notebooks ermöglichen das Kopieren und Einfügen von Zellen vscode#104176](https://github.com/microsoft/vscode/issues/104176)
> * [x]  Renderer muss mit der Erweiterung kommunizieren (wir können dies tun, aber wie können Renderer & Erweiterung die Ausgabe eindeutig identifizieren. Die outputId ist in einer Notebook-Zellenausgabe nicht verfügbar). [Hinzufügen `von Produkt` und `runCommand` auf Notebook-Renderer-API vscode#103864 (Kommentar)](https://github.com/microsoft/vscode/issues/103864#issuecomment-675132563)
> * [x]  Clearing-Zelle sollte Ausführung löschen, Ausführungszeiten Auftrag https://github.com/microsoft/vscode-python/issues/13159, 
>   * Geben Sie vorzugsweise ein Ereignis an, damit wir wissen, dass der Benutzer eine Zelle gelöscht hat.
>   * Wir müssen auch in der Lage sein, Dokumente als schmutzig zu markieren.
>   * [Notebook-Ausführungsmodell-API (+ klare Ausgabenebeneffekte) vscode#103713](https://github.com/microsoft/vscode/issues/103713)
> * Das Löschen von Zellen sollte eine Änderung im Notizbuch auslösen [Notebook-Ausführungsmodell-API (+ klare Ausgabenebeneffekte) vscode#103713](https://github.com/microsoft/vscode/issues/103713)
> * [x]  Kernel-Story (es gab Probleme mit dem aktuellen Design und wir warteten darauf, dass das Personal aus dem Urlaub zurückkehrte)
> * [x]  VIM-Tastatur, kann https://github.com/microsoft/vscode-python/issues/12822 nicht entkommen
> * [x]  Intellisense für Zellen (LS benötigt ein einzelnes Dokument oder wir benötigen eine Änderung in LSP)
> * [x]  Führen Sie alle unten / alle oben aus [Erweiterungen erlauben, Zellenbefehle mit Zellargumenten vscode#98282 aufzurufen](https://github.com/microsoft/vscode/issues/98282)
> * [ ]  Bilder mit relativen Pfaden in der Markdown/HTML-Ausgabe für unbenannte Dateien [Unterstützt relative Pfade für Bilder in Markdown-/Rich-Output-Zellen (von unbenannten Notebooks) vscode#99139](https://github.com/microsoft/vscode/issues/99139)
> * [x]  Das Senden von Nachrichten an Notebook-Renderer funktioniert nicht (ist dies ein bekanntes Problem?)
> * [x]  Können wir einen dritten Zelltyp (Markdown, Code & raw) https://github.com/microsoft/vscode-python/issues/7952 haben`raw`
>   
>   * Kann die Erweiterung zu Zelltypen beitragen?
>   * Möglicherweise ein guter Zeitpunkt, um auch Superzellen zu betrachten (also haben wir Code, Markdown, Rohkost, Super, etc.), Dinge, die Erweiterungen beitragen
> * [x]  CI-Tests scheitern hin und wieder https://dev.azure.com/ms/vscode-python/_build/results?buildId=97479&view=logs&j=97f6daac-606a-5b3e-ec4c-7c15dc363dc1&t=377cca0f-8a41-5fa6-e993-ec4a6587bd59
> * [x]  Rückrufe von gerendertem HTML an eine Erweiterung funktionieren nicht [Nachricht aus gerenderter HTML-Ausgabe kann nicht an NotebookEditor vscode#98353 gesendet werden](https://github.com/microsoft/vscode/issues/98353)
> * [x]  Renderer rendern die Ausgabe nicht, wenn die benutzerdefinierte Rendererausgabe nicht die Standardausgabe ist (d. h. wenn der Benutzer den benutzerdefinierten Renderer auswählen muss, funktioniert er nicht).
> * [x]  Interrupt-Kernel (Unterstützung mehrerer Abbrüche) [Hinzufügen von Unterstützung für mehrfache Abbrüche in der Notebook-Stopptaste vscode#99203 ](https://github.com/microsoft/vscode/issues/99203)
> * [x]  Links in Markdown und Ausgabe [Unterstützung für benutzerdefinierte Linkhandler in Markdown Cell und Webviews vscode#98100](https://github.com/microsoft/vscode/issues/98100)
> * [x]  Tastenkombinationen für Befehle, die nicht funktionieren [Erneutes Aufrufen zum Ausblenden von Verknüpfungen vscode#104860](https://github.com/microsoft/vscode/issues/104860)
> 
> ### GA Checkliste
> * [x]  Variabler Viewer
> * [x]  Plot-Viewer
> * [x]  Ipywidgets (Don WIP)
> * [x]  Sprachfunktionen 
>   * [x]  Hilfe zu AutoVervollständigung, Hover, Signatur
> * [x]  Kerne 
>   * [x]  Bevorzugter Kernel funktioniert nicht
>   * [x]  Auswahl des lokalen Kernels
>   * [x]  Auswahl von Remote-Kernels
>   * [x]  Kerne (Andere Sprachen)
> * [x]  Versammeln
> * [x]  Remote-Jupyter
> * [ ]  Jupyter-Aktivitätsleiste
> * [x]  Per Linie laufen
> * [ ]  Rohe Zellen?
> * [ ]  Erweiterte Sprachfunktionen 
>   * [ ]  Formatierung
>   * [ ]  Linting
>   * [ ]  Refactoring
>   * [ ]  Sort imports
>   * [ ]  Goto def
> * [ ]  Live share (needs to be tested with widgets, plots, run by line, gather)
> * [ ]  Use new NB for start page (this must be used when users are in experiment) - hopefully nothing to do here.
> * [ ]  Refactor to remove old code (transition to new stuff), there's an issue for this
> * [ ]  Run all below/all above (command, do we need icons?)
> * [ ]  Update nterat in renderers
> * [ ]  Renderers extension
> * [ ]  Using renderer extension scripts in interactive window
> * [x]  White backgrounds for vega plots
> * [x]  White backgrounds for SVGs (e.g. axes in  aren't visible in dark mode)`plt.plot`
> * [x]  Verify that renaming notebooks works
> * [x]  Trusted notebooks
> * [x]  Export (pdf/html) - should be the easiest from this entire list
> * [ ]  Full blown debugger
> 
> Breakdown

**Comment by WouterVanGoey** [comment]
Hi, any news on when linting will work in Jupyter notebooks running in VS Code?

**Comment by 0xSynth** [comment]
Yes, I second this question, linting in Jupyter notebooks running in VSCode is badly needed

**Comment by jrich100** [comment]
@DonJayamanne Any info on the prioritization of type checking/linting in notebooks?

**Comment by Fissium** [comment]
Hi, any info on linting in notebooks?
