### ISSUE TITLE
Jupyter: Iteration Plan for January 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#12474]
This plan captures our work in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/170413). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Outputs
- [x] On notebook restore, fallback if an `ipywidget` needs an active kernel connection [vscode-jupyter#8635](https://github.com/microsoft/vscode-jupyter/issues/8635) @DonJayamanne @mjbvz
- [ ] :muscle: Support `ipywidget 8` [vscode-jupyter#8552](https://github.com/microsoft/vscode-jupyter/issues/8552) @DonJayamanne

### Kernels
- [ ] :runner: Continued polish of the Kernel Picker [vscode-jupyter#11904](https://github.com/microsoft/vscode-jupyter/issues/11904) @rebornix @DonJayamanne
- [x] Adopt activate function for loading kernel and notebook preloads [vscode-jupyter#11817](https://github.com/microsoft/vscode-jupyter/issues/11817) @DonJayamanne
- [x] Wrong elapsed time reported [vscode-jupyter#12399](https://github.com/microsoft/vscode-jupyter/issues/12399) @DonJayamanne

### Debugging
- [ ] :runner: Allow disabling "justMyCode" in Interactive Window with `ipykernel` debugging [vscode-jupyter#11777](https://github.com/microsoft/vscode-jupyter/issues/11777) @roblourens
- [ ] :runner: Investigate `debugpy` hangs in Jupyter debugging [debugpy#1051](https://github.com/microsoft/debugpy/issues/1051) @roblourens
- [x] Fix IW debugging [vscode-jupyter#12407](https://github.com/microsoft/vscode-jupyter/issues/12407) @roblourens
- [x] Improve presentation of the cell that is being debugged [microsoft/vscode#169190](https://github.com/microsoft/vscode/issues/169190) @roblourens

### Interactive Window
- [x] Cleanup the IW context menu [vscode-jupyter#12392](https://github.com/microsoft/vscode-jupyter/issues/12392) @amunger
- [ ] :muscle: Clean up Interactive Window creation/restore [vscode-jupyter#10808](https://github.com/microsoft/vscode-jupyter/issues/10808) @amunger

### Engineering
- [x] Update localization to use `l10n.t` API  [vscode-jupyter#12508](https://github.com/microsoft/vscode-jupyter/issues/12508) @DonJayamanne

-----
### Deferred
- [ ] Make it easier to distinguish between IW and notebook settings [vscode-jupyter#12393](https://github.com/microsoft/vscode-jupyter/issues/12393) @amunger
- [ ] Resolve keyboard binding conflicts [vscode-jupyter#12394](https://github.com/microsoft/vscode-jupyter/issues/12394) @amunger
- [ ] Introduce a "Run in IW" launch config [vscode-jupyter#7683](https://github.com/microsoft/vscode-jupyter/issues/7683) @amunger
- [ ] Explore files synchronization for Jupyter servers [vscode-jupyter#1601](https://github.com/microsoft/vscode-jupyter/issues/1601) @rebornix @DonJayamanne
- [ ] Improve remote jupyter server CORS warning/error message prompt [vscode-jupyter#12507](https://github.com/microsoft/vscode-jupyter/issues/12507) @DonJayamanne
- [ ] Kernel architecture review and polish [vscode-jupyter#10832](https://github.com/microsoft/vscode-jupyter/pull/10832) @rebornix @DonJayamanne
- [ ] Debugging/debugger architecture review and polish [vscode-jupyter#11108](https://github.com/microsoft/vscode-jupyter/issues/11108) @roblourens
- [ ] Enable `ipykernel 6` debugging in the interactive window [query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+forceIPyKernelDebugger) @roblourens
