### ISSUE TITLE
Jupyter: Iteration Plan for February 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#12734]
This plan captures our work in **February 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/173445). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Support `ipywidget 8` [vscode-jupyter#8552](https://github.com/microsoft/vscode-jupyter/issues/8552) @DonJayamanne
- [x] Ensure the cell tag view is not visible by default @rebornix [microsoft/vscode-jupyter-cell-tags#22](https://github.com/microsoft/vscode-jupyter-cell-tags/pull/22)
- [x] Remove Jupyter error renderer and support multiple versions of ipykernel call stacks [vscode-jupyter#12285](https://github.com/microsoft/vscode-jupyter/issues/12285) @rebornix @amunger
- [ ] :muscle: Explore files synchronization for Jupyter servers [vscode-jupyter#1601](https://github.com/microsoft/vscode-jupyter/issues/1601) @rebornix @DonJayamanne
- [x] Improve remote jupyter server CORS warning/error message prompt [vscode-jupyter#12507](https://github.com/microsoft/vscode-jupyter/issues/12507) @DonJayamanne

### Kernels
- [x] Continued polish of the Kernel Picker [vscode-jupyter#11904](https://github.com/microsoft/vscode-jupyter/issues/11904) @rebornix @DonJayamanne
- [ ] :hand: Conda environments without an Python interpreter are not listed in the Kernel Picker [vscode-jupyter#11855](https://github.com/microsoft/vscode-jupyter/issues/11855) @DonJayamanne

### Debugging
- [ ] :runner: Allow disabling "justMyCode" in Interactive Window with `ipykernel` debugging [vscode-jupyter#11777](https://github.com/microsoft/vscode-jupyter/issues/11777) @roblourens
- [ ] :runner: Investigate `debugpy` hangs in Jupyter debugging [debugpy#1051](https://github.com/microsoft/debugpy/issues/1051) @roblourens
- [ ] :muscle: Use `setPydevdSourceMap` for IW and Notebook debugging [vscode-jupyter#12643](https://github.com/microsoft/vscode-jupyter/issues/12643) @roblourens
- [ ] :muscle: Support subprocess debugging with Jupyter [vscode-jupyter#9886](https://github.com/microsoft/vscode-jupyter/issues/9886) @roblourens

### Interactive Window
- [x] Make it easier to distinguish between IW and notebook settings [vscode-jupyter#12393](https://github.com/microsoft/vscode-jupyter/issues/12393) @amunger
- [x] Resolve keyboard binding conflicts [vscode-jupyter#12394](https://github.com/microsoft/vscode-jupyter/issues/12394) @amunger
- [x] Improve selection of kernels in the IW [vscode-jupyter#11967](https://github.com/microsoft/vscode-jupyter/issues/11967) @amunger

### Engineering
- None.

-----
### Deferred
- [ ] Review how we start local Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12831) @DonJayamanne
- [ ] Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12832)  @DonJayamanne
- [ ] Clean up Interactive Window creation/restore [vscode-jupyter#10808](https://github.com/microsoft/vscode-jupyter/issues/10808) @amunger
