### ISSUE TITLE
Jupyter: Iteration Plan for March 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#12994]
This plan captures our work in **March 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/176147). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Create a Data Science built-in profile https://github.com/microsoft/vscode/issues/166359 @minsa110
- [ ] :muscle: Explore files synchronization for Jupyter servers [vscode-jupyter#1601](https://github.com/microsoft/vscode-jupyter/issues/1601) @rebornix @DonJayamanne

### Kernels
- [x] Adopt quick pick hover for kernel picker [vscode-jupyter#13086](https://github.com/microsoft/vscode-jupyter/issues/13086) @DonJayamanne @TylerLeonhardt
- [ ] Mitigation for upstream kernel issues  @DonJayamanne
  - [x] Jupyter notebook slow start/connection  [jupyter/jupyter_client#926](https://github.com/jupyter/jupyter_client/issues/926)
  - [x] Kernels crash/restart [jupyter/notebook#6721](https://github.com/jupyter/notebook/issues/6721)
  - [ ] :runner: Build zmq binaries for Apple Silicon [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206)
- [x] Conda environments without an Python interpreter are not listed in the Kernel Picker [vscode-jupyter#11855](https://github.com/microsoft/vscode-jupyter/issues/11855) @DonJayamanne

### Engineering
- [ ] :runner: Explore adoption of platform specific extensions [vscode-jupyter/#13085](https://github.com/microsoft/vscode-jupyter/issues/13085) @DonJayamanne @rebornix
- [ ] :muscle: Review how we start local Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12831) @DonJayamanne
- [ ] :muscle: Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12832)  @DonJayamanne

-----
### Deferred
- [ ] :runner: Allow disabling "justMyCode" in Interactive Window with `ipykernel` debugging [vscode-jupyter#11777](https://github.com/microsoft/vscode-jupyter/issues/11777) @roblourens
- [ ] :runner: Investigate `debugpy` hangs in Jupyter debugging [debugpy#1051](https://github.com/microsoft/debugpy/issues/1051) @roblourens
- [ ] :muscle: Use `setPydevdSourceMap` for IW and Notebook debugging [vscode-jupyter#12643](https://github.com/microsoft/vscode-jupyter/issues/12643) @roblourens
- [ ] :muscle: Support subprocess debugging with Jupyter [vscode-jupyter#9886](https://github.com/microsoft/vscode-jupyter/issues/9886) @roblourens
