### ISSUE TITLE
Data Viewer in VS Code should have automatic colored cells, automatic column width, number format option, floating window option, expression evaluation

### ISSUE THREAD

**Issue by costabm** [microsoft/vscode-jupyter#13113]
![image](https://user-images.githubusercontent.com/57107560/225701122-d182df93-7999-4458-8892-5fb4c881435c.png)
```[tasklist]
### Tasks
- [ ] automatic colored cells
- [ ] automatic column width
- [ ] number format option
- [ ] floating window option
- [ ] expression evaluation
```

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
