### ISSUE TITLE
Jupyter: Iteration Plan for April 2023 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#13250]
This plan captures our work in **April 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/178951). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [ ] :red_circle: Adopt `onWillSaveNotebookDocument` in image attachment cleaner @yoyokrazy
- [ ] :red_circle: Explore support for `notebook.codeActionsOnSave` @yoyokrazy
- [ ] Add "Restart and run all", "Restart and run above" kernel management commands @yoyokrazy

### Kernels
- [ ] :red_circle: Missing C++ runtime caused zeromq to fail on Windows @DonJayamanne
- [ ] :red_circle: Provide API to open a notebook and preselect a specific kernel @DonJayamanne
- [ ] :red_circle: Show whether a kernel is busy when reconnecting after reload @DonJayamanne
- [ ] :red_circle: :muscle: Explore reconnecting a running cell after reload @DonJayamanne 

### Codespaces
- [ ] :red_circle: Explore how to keep a codespace alive on long-running cell executions @rebornix

### Engineering
- [ ] :runner: Explore adoption of platform specific extensions [vscode-jupyter/#13085](https://github.com/microsoft/vscode-jupyter/issues/13085) @DonJayamanne @rebornix
- [ ] :muscle: Review how we start local Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12831) @DonJayamanne
- [ ] :muscle: Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/12832)  @DonJayamanne

-----
### Deferred
- [ ] :muscle: Explore files synchronization for Jupyter servers [vscode-jupyter#1601](https://github.com/microsoft/vscode-jupyter/issues/1601) @rebornix @DonJayamanne
- [ ] :runner: Allow disabling "justMyCode" in Interactive Window with `ipykernel` debugging [vscode-jupyter#11777](https://github.com/microsoft/vscode-jupyter/issues/11777) @roblourens
- [ ] :runner: Investigate `debugpy` hangs in Jupyter debugging [debugpy#1051](https://github.com/microsoft/debugpy/issues/1051) @roblourens
- [ ] :muscle: Use `setPydevdSourceMap` for IW and Notebook debugging [vscode-jupyter#12643](https://github.com/microsoft/vscode-jupyter/issues/12643) @roblourens
- [ ] :muscle: Support subprocess debugging with Jupyter [vscode-jupyter#9886](https://github.com/microsoft/vscode-jupyter/issues/9886) @roblourens
