### ISSUE TITLE
Jupyter: Iteration Plan for May 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#13471]
This plan captures our work in **May 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/181778). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Kernels
- [x] Explore reconnecting a running (remote kernel) cell after reload [vscode-jupyter#13276](https://github.com/microsoft/vscode-jupyter/issues/13276) @DonJayamanne
- [x] Replace kernel filter UI with a filter setting  [vscode-jupyter#13414](https://github.com/microsoft/vscode-jupyter/issues/13414) @DonJayamanne
- [x] Explore improving interoperability for session between VS Code and Jupyter [vscode-jupyter#13424](https://github.com/microsoft/vscode-jupyter/issues/13424) @DonJayamanne

### Codespaces
- None.

### Engineering
- [x] Improve ZMQ builds [vscode-jupyter#13479](https://github.com/microsoft/vscode-jupyter/issues/13479) @DonJayamanne @deepak1556
- [ ] :muscle: Review how we start local Jupyter Servers [vscode-jupyter#12831](https://github.com/microsoft/vscode-jupyter/issues/12831) @DonJayamanne
- [ ] :runner: Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter#12832](https://github.com/microsoft/vscode-jupyter/issues/12832) @DonJayamanne

-----
### Deferred
- None.
