### ISSUE TITLE
Jupyter: Iteration Plan for June 2023 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#13682]
This plan captures our work on the Jupyter Extension in **June 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/184844). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- None.

### Kernels
- [ ] Faster display of Python environments in Kernel Picker [vscode-jupyter#13653](https://github.com/microsoft/vscode-jupyter/issues/13653), upstream [vscode-python#21271](https://github.com/microsoft/vscode-python/issues/21271) @DonJayamanne

### Remote Jupyter Server
- [ ] Unify the storage for server uris (experimental) [vscode-jupyter#11645](https://github.com/microsoft/vscode-jupyter/issues/11645) @DonJayamanne
- [ ] :red_circle: Move password manager into UserJupyterServer plugin @DonJayamanne
- [ ] :red_circle: Export Notebook for Web: call `JupyterLab#ContentManager` directly to simplify `JupyterKernelSession` @DonJayamanne
- [ ] :red_circle: :muscle: Remove usage of URI and ServerId as identifier for Jupyter Servers @DonJayamanne

### Codespaces
- None.

### Engineering
- [ ] :red_circle: :runner: Update Experimental Service npm package to latest @DonJayamanne

-----
### Deferred
- [ ] :runner: Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter#12832](https://github.com/microsoft/vscode-jupyter/issues/12832) @DonJayamanne
