### ISSUE TITLE
Jupyter: Iteration Plan for July 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#13885]
This plan captures our work on the Jupyter Extension in **July 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/187398). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- [x] Interactive Window system messaging improvements [vscode-jupyter#13871](https://github.com/microsoft/vscode-jupyter/issues/13871) @amunger

### Remote Jupyter Server
- [x] Remove usage of URI and ServerId as identifier for Jupyter Servers [vscode-jupyter#13632](https://github.com/microsoft/vscode-jupyter/issues/13632) @DonJayamanne
- [x] Review API `JupyterServerProvider` and prepare for stable API [vscode-jupyter#13894](https://github.com/microsoft/vscode-jupyter/issues/13894) @DonJayamanne @rebornix
- [ ] :muscle: Remove extra click for remote jupyter server connection [vscode-jupyter#13892](https://github.com/microsoft/vscode-jupyter/issues/13892) @DonJayamanne
- [ ] :muscle: Investigate API support for kernel startup prehook [vscode-jupyter#13893](https://github.com/microsoft/vscode-jupyter/issues/13893) @rebornix @DonJayamanne

### Codespaces
- [x] Support 'Continue On...' for Jupyter Notebook [vscode-jupyter#13895](https://github.com/microsoft/vscode-jupyter/issues/13895) @rebornix

### Engineering
- None.

-----
### Deferred
- [ ] :runner: Explore how to simplify the code for managing connections to local and remote Jupyter Servers [vscode-jupyter#12832](https://github.com/microsoft/vscode-jupyter/issues/12832) @DonJayamanne
