### ISSUE TITLE
Moving Jupyter Hub support to a separate extension

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13973]
Currently we support an old version of Jupyter Hub but not the latest. With the introduction of stable api, we could move the Jupyter Hub support to a separate extension, which can potentially get community help for supporting all versions of Jupyter Hub.
```[tasklist]
### Tasks
- [x] Verify server is already running (before starting a kernel or testing the connection)
- [ ] Migrate existing connections
- [x] Store base URL and not full url in global storage
- [x] Test to verify we can start a kernel with the Auth information (enumerating kernels via API is not sufficient)
- [x] Store username/password
- [x] Prompt for username/password or a Token (token might work in web)
- [x] Create Repo, setup Pre-release & release pipelines, CG, etc
- [x] After trying that in the browser, I figured this out as in the browser it's a 5xx error. It would be great if the error message we present is more accurate but I guess it's a corner case as usually users already have jupyter hub running successfully. See https://github.com/microsoft/vscode-jupyter/issues/14202#issuecomment-1697859532
```

**Comment by DonJayamanne** [comment]
Marking as completed
