### ISSUE TITLE
Migrate from the old PythonEnvironment types/API to the new Python Extension API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14038]
The Old PythonEnvironment type is used all over the code, Python extension has officially changed their types.
Thus we're having to translate the stable API types into old outdated types in our codebse.

We need to move away from the old deprecated types.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14039
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14049
- [ ] Use new types in local kernel spec finder
- [ ] Use new types in LSP
- [ ] Use new types in spawning Local Python Kernels
- [ ] Use new types in debugger
- [ ] Use new types in Kernel Finders
- [ ] Use new types in Notebook Controllers
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14055
- [ ] https://github.com/microsoft/vscode-jupyter/issues/14057
- [ ] Use new Python API types in Installers
- [ ] Remove sysPrefix, sysVersion, version, from old Python API
- [ ] https://github.com/microsoft/vscode-jupyter/issues/15140
```

**Comment by DonJayamanne** [comment]
Done
