### ISSUE TITLE
Jupyter: Iteration Plan for August 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#14069]
This plan captures our work on the Jupyter Extension in **August 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/189778). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :repeat:            | repeating activity from iteration to iteration    |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### General
- None.

### API
- [ ] :runner: Finalize API `JupyterServerProvider` [vscode-jupyter#13894](https://github.com/microsoft/vscode-jupyter/issues/13894) and onboard AML @DonJayamanne

### Remote Jupyter Server
- [x] Investigate API support for kernel startup prehook [vscode-jupyter#13893](https://github.com/microsoft/vscode-jupyter/issues/13893) @DonJayamanne
- [x] Remove extra click for remote jupyter server connection [vscode-jupyter#13892](https://github.com/microsoft/vscode-jupyter/issues/13892) @DonJayamanne
- [ ] :runner: Plan for moving Jupyter Hub support to a separate extension [vscode-jupyter#13973](https://github.com/microsoft/vscode-jupyter/issues/13973) @DonJayamanne

### Kernels
- [ ] :muscle: Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne

### Engineering
- None.

-----
### Deferred
- None.
