### ISSUE TITLE
Renderer extension for new Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1423]
If and when we decide to publish a separate renderer extension.

https://github.com/microsoft/vscode-notebook-renderers

- [ ] Review Extension information
	- name, id, description, license
	- readme
	- contribution doc
- [ ] We need to update the renderer API in renderer extension as we did here: 
https://github.com/microsoft/vscode-python/pull/13665/files
Changes related to the following need to be applied to renderer extension:
	* [index.tsx](https://github.com/microsoft/vscode-python/pull/13665/files#diff-e9d196ad86eab236c4a11ac079541dc7)https://github.com/microsoft/vscode-python/pull/13665/files#diff-e9d196ad86eab236c4a11ac079541dc7
	* [package.json](https://github.com/microsoft/vscode-python/pull/13665/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)https://github.com/microsoft/vscode-python/pull/13665/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

- [ ] After publishing extension, remove related renderer code from DS code (from Python extension)

* [ ] Component governance
* [ ] Version, publisher id, links to repo, issue link, (package.json)
* [ ] Third party notices file
* [ ] Usual MD files (lic, sec, contibuting, code of conduct, etc)
* [ ] Ship with VS Code core (as dependent extension?)
* [ ] Azo Project
