### ISSUE TITLE
Explore moving Tensorboard support from Python extension to its own

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14472]
```[tasklist]
### Tasks
- [x] Migrate  commands, setting and key binding to ext
- [ ] API requirements https://github.com/microsoft/vscode-python/issues/22174
- [x] How do we migrate the commands?
- [x] Migrate logDirectory setting or leave it under python? (Python ext will not have to care aboud this)
```

**Comment by DonJayamanne** [comment]
# How do we migrate the commands?
* Leave it there
* When command is selected & tensorboard is not installed, prompt to install tensorboard extension
* When command is selected & tensorboard is installed, warn them that the command is deprecated and will be removed.

**Comment by DonJayamanne** [comment]
Closing this as completed

**Comment by DonJayamanne** [comment]
We have a test plan item that validates this.
