### ISSUE TITLE
Ship Jupyter extension with Python DS parity

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#183]
* [ ] Review Extension
	* [ ] Branding (image, background etc)
	* [ ] Readme
	* [ ] Contribution guide
	* [ ] Change log

**CI**
* [ ] Update vsix names in the GitHub Workflow files
	* Currently pointing to `ms-python-insiders-nods.vsix`.
* [ ] Update Python CI pipelines to download Jupyter VSIX

**Features to validate**
* [ ] Survey links (are these correct)
* [ ] Startup Telemetry
* [ ] Telemetry (confirm it works & we get this)
* [ ] Telemetry dashboards (migrate or add new extension)
* [ ] Insiders build (this must get updated daily)
* [x] Jupyter Output panel (display relevant info)
* [x] Install python extension when installing this extension (when opening a python based notebook)
* [x] Test migration of existing user
	* [x] Install old extension, then install new extension, validate it works without a hitch.
* [x] Experiments
* [ ] Interactive window
	* [x] Running cells
	* [x] Interrupting
	* [x] Restarting kernels
	* [x] IPyWidgets
	* [x] Plot viewer
	* [x] Connecting to remote jupyter
	* [ ] Live share
* [ ] Old, custom Notebook
	* [x] Selecting kernels
	* [x] Running cells
	* [x] Restarting kernels
	* [x] Interrupting
	* [x] IPyWidgets
	* [x] Plot viewer
	* [x] Connecting to remote jupyter
	* [ ] ~~Live share (this never worked before)~~
* [ ] Running extension inside docker container
	* [ ] Interactive window
	* [ ] Custom, & old notebooks
* [x] Native notebooks (ensure this works)
* [ ] Gather
* [ ] AML Extension
* [ ] PySpark Extension
* [x] Trusting notebooks
* [x] Run by line
* [x] Export to pdf, python script
* [x] Export interactive to ipynb
* [x] Non-Python kernels in old, custom noteooks
* [x] Debugger in interactive window
* [ ] Variable explorer in 
	* [x] interactive window
	* [x] old notebook
	* [ ] custom editor
* [ ] Keyboard shortcuts for interactive window
	* [x] We must test all (as the context keys have changed), & we have changes in Python extension
* [ ] Keyboard shorcuts for notebooks (not native)
	* [ ] We must test all (as the context keys have changed), & we have changes in Python extension
