### ISSUE TITLE
Data Wrangler Issue Tracker

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#5941]
Things that we should do
- [ ] Add support for vertical scrolling in the Data Wrangler side panel
- [ ] Add support for CTRL + Z to undo operations in the Data Wrangler (should remove code cell, remove most recent operation in the history list, remove the last line of code added in the code section of the side panel, and update the data viewer to show the previous state of the data)
- [ ] Rename "Drop NA" to "Remove missing values" (this is the same wording the pandas API uses)
- [ ] Hide the data viewer refresh button in the standalone data wrangler view
- [ ] Add indicator for which columns have missing data (requires design input)
- [ ] Add DF Describe stats to the side panel (requires design input/spec)
- [ ] Add preview mode for all data cleaning operations (requires design input/spec)

Things that require more discussion and thought
- [ ] Add support to join/merge multiple datasets
- [ ] Figure out what to do with the index column for non transposed data frames
