### ISSUE TITLE
Implement persistent native interactive window sessions

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6460]
We recently implemented being able to restore the contents of the interactive window from backup between VS Code reloads. However, there are a number of issues that need to be resolved in order for this experience to work smoothly.

The current behavior:
- Reload 
- Interactive window is still open with all the cells from the previous session
- Mapping between Python file and interactive window is _lost_
- Kernel is initially dead (killed on reload). After waiting a bit, the previously connected kernel gets restarted, and a new connection sys info cell is appended to the interactive window (weird behavior for users--user expectation here is that it's the same kernel connection)

Discussion topic: What is the meaning of hot exit, and why does it exist?
    - Is it just about persisting the history in the interactive window, or is it also about having a persistent kernel connection?
    - Currently the implementation supports the former, i.e. we keep the cells around but the kernel session is lost
    - One perspective: if I reload VS Code, I don't want to lose my interactive window session--that means the mapping between the Python file and interactive window should still be there, _and_ the kernel connection should still be live and I should not lose my kernel state https://github.com/microsoft/vscode-jupyter/issues/6420

Work items
- [ ] Persist a mapping between the active #%% Python file and the interactive window, and restore this mapping on reload https://github.com/microsoft/vscode-jupyter/issues/6421
- [ ] Add support for explicit raw kernel session management (don't auto kill on reload) https://github.com/microsoft/vscode-jupyter/issues/6420
- [ ] Ensure controller connection isn't lost https://github.com/microsoft/vscode-jupyter/issues/6419

**Comment by amunger** [comment]
Created a more up to date [discussion thread](https://github.com/microsoft/vscode-jupyter/discussions/9583) for this
