### ISSUE TITLE
Jupyter: Iteration Plan for July 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6628]
This plan captures our work in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/128444). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Notebooks
- [x] :red_circle: Switch all users over to use VS Code built-in notebooks @claudiaregio
- [x] Bring plot viewer support to built-in notebooks [vscode-jupyter#6315](https://github.com/microsoft/vscode-jupyter/issues/6315) @DonJayamanne
- [ ] :runner: Support run by line [vscode-jupyter#5607](https://github.com/microsoft/vscode-jupyter/issues/5607) @DavidKutu @roblourens

### Interactive Window
- [x] Address all issues blocking the built-in interactive window from being the default https://github.com/microsoft/vscode-jupyter/blob/main/.vscode/notebooks/jupyter.github-issues @joyceerhl @rebornix @rchiodo
- [x] :muscle: Explore using the interactive window as a console for notebook kernels [vscode-jupyter#6765](https://github.com/microsoft/vscode-jupyter/issues/6765) @joyceerhl @rebornix

### Documentation 
- [x] :red_circle: Update documentation to use built-in notebooks @claudiaregio **team**
- [x] :red_circle: Move documentation to `https://code.visualstudio.com/docs` @claudiaregio @gregvanl

### Engineering
- [ ] :red_circle: :muscle: :runner: Simplify Code clean-up/simplification in the Jupyter extension @greazer **team**
- [ ] :red_circle: :muscle: Explore separating the default output renders into their own extension @greazer **team**

### Deferred
- [ ] Placeholder kernel to ensure run button appears immediately in a notebook [vscode-jupyter#5861](https://github.com/microsoft/vscode-jupyter/issues/5861) @DonJayamanne
   - Add telemetry to get perf times for loading python & non-python kernels for the first time (without cache)
   - Discuss with Python team to improve perf around discovering Python interpreters
