### ISSUE TITLE
Jupyter: Iteration Plan for August 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#7008]
This plan captures our work in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/130368). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Notebooks
- [ ] :runner: Support run by line [vscode-jupyter#5607](https://github.com/microsoft/vscode-jupyter/issues/5607) @DavidKutu @roblourens
- [ ] :runner: Support full debugging [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @roblourens @DavidKutu
- [ ] :runner: Review Survey prompt behavior (first prompt, wait between prompts) [vscode-jupyter-internal#189](https://github.com/microsoft/vscode-jupyter-internal/issues/189) @IanMatthewHuff @claudiaregio
- [x] Notebooks performance [vscode-jupyter#6941](https://github.com/microsoft/vscode-jupyter/issues/6941), [vscode-jupyter#5662](https://github.com/microsoft/vscode-jupyter/issues/5662), [vscode#129370](https://github.com/microsoft/vscode/issues/129370) @DonJayamanne @rebornix
- [x] :muscle: Explore handling and generation of SVG [vscode-jupyter#6913](https://github.com/microsoft/vscode-jupyter/issues/6913) @IanMatthewHuff

### Python Notebooks
- [x] Diagnostics on cell deletion: [vscode-jupyter#6608](https://github.com/microsoft/vscode-jupyter/issues/6608) @rchiodo @rebornix
- [x] :muscle: Ignore magic commands [vscode-jupyter#6635](https://github.com/microsoft/vscode-jupyter/issues/6635) @rchiodo
- [ ] :runner: :muscle: Explore dissonance between interpreters and kernels [vscode-jupyter#6333](https://github.com/microsoft/vscode-jupyter/issues/6333) @brettcannon @rchiodo

### Interactive Window
- [ ] :runner: Polish interactive window: [vscode-jupyter#7168](https://github.com/microsoft/vscode-jupyter/issues/7168) @joyceerhl

### Documentation 
- None.

### Engineering
- [ ] :runner: Simplify Code clean-up/simplification in the Jupyter extension @DonJayamanne @joyceerhl [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950), [vscode-jupyter#6488](https://github.com/microsoft/vscode-jupyter/issues/6488)
- [ ] :muscle: Explore separating the default output renders into their own extension @greazer **team** [vscode-jupyter#1909](https://github.com/microsoft/vscode-jupyter/issues/1909)

### Deferred
- [ ] Placeholder kernel to ensure run button appears immediately in a notebook [vscode-jupyter#5861](https://github.com/microsoft/vscode-jupyter/issues/5861) @DonJayamanne
   - Add telemetry to get perf times for loading python & non-python kernels for the first time (without cache)
