### ISSUE TITLE
Polish interactive window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7168]
We shipped a native interactive window experience in the July release. This issue tracks polishing the interactive window experience.

Done
- [x] Variable explorer should be populated when focus is in script file https://github.com/microsoft/vscode-jupyter/issues/6993 
- [x] Fix interrupt/restart https://github.com/microsoft/vscode-jupyter/issues/7081 
- [x] Provide some solution for `esc` and `ctrl+u` clearing the interactive window input box https://github.com/microsoft/vscode-jupyter/issues/7157
- [x] Context keys are not correctly set https://github.com/microsoft/vscode-jupyter/issues/7158
- [x] Support or deprecate missing settings https://github.com/microsoft/vscode-jupyter/issues/7031, https://github.com/microsoft/vscode-jupyter/issues/7094
- [x] Execution count incorrect https://github.com/microsoft/vscode-jupyter/issues/7156
- [x] Code dedented on IW export https://github.com/microsoft/vscode-jupyter/issues/7088
- [x] No execution time set https://github.com/microsoft/vscode-jupyter/issues/7162
- [x] https://github.com/microsoft/vscode-jupyter/issues/7013
- [x] https://github.com/microsoft/vscode-jupyter/issues/6881
- [x] https://github.com/microsoft/vscode-jupyter/issues/7303
- [x] Delete cell usability: 
 https://github.com/microsoft/vscode-jupyter/issues/7188, https://github.com/microsoft/vscode-jupyter/issues/7250, https://github.com/microsoft/vscode-jupyter/issues/6475
- [x] https://github.com/microsoft/vscode-jupyter/issues/7288
- [x] https://github.com/microsoft/vscode-jupyter/issues/7269
- [x] https://github.com/microsoft/vscode-jupyter/issues/7476
- [x] https://github.com/microsoft/vscode-jupyter/issues/7366
- [x] https://github.com/microsoft/vscode-jupyter/issues/7280

Upstream
- https://github.com/microsoft/vscode/issues/131659
- https://github.com/microsoft/vscode/issues/132064

Deferred
- Rework command queuing https://github.com/microsoft/vscode-jupyter/issues/7164, https://github.com/microsoft/vscode/issues/130295

**Comment by ihnorton** [comment]
Not sure if you want separate issue for this, but one minor tweak is that I would like to see the spinner or completion checkbox regardless of the number of lines of the input cell. Currently, when I send a number of cells to the interactive window from a cell-delimited (`#%%`) script file, then each execution cell is collapsed and it is hard to tell whether execution has completed (have to expand the cell to see the spinner/checkbox)

**Comment by thor4** [comment]
Thanks for this helpful list @joyceerhl. Should [#7065](https://github.com/microsoft/vscode-jupyter/issues/7065) also be included here?

**Comment by joyceerhl** [comment]
@ihnorton In the current Insiders build and upcoming Stable release, we will display a blue progress bar above each cell that is executing--this is the same progress bar that is displayed when the cell is expanded, and @rebornix pushed a change to ensure that the progress bar is also displayed when the cell is collapsed. Hopefully that is a slight improvement for now.

@thor4 #7065 was an existing issue with the variable explorer for native notebooks so should be addressed outside of this issue, which tracks interactive window-specific issues.

**Comment by joyceerhl** [comment]
Will tackle https://github.com/microsoft/vscode/issues/130295 at the start of next iteration as it involves a somewhat risky refactor. All remaining issues are either upstream (discussing solutions with @rebornix) or fixed in Insiders.
