### ISSUE TITLE
Jupyter: Iteration Plan for September 2021 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-jupyter#7428]
This plan captures our work in **September**. We follow the same iteration cycle as [VS Code](). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Notebooks
- [x] Polish run by line [vscode-jupyter#5607](https://github.com/microsoft/vscode-jupyter/issues/5607) @DavidKutu @roblourens
- [x] Ship a reasonable full debugging experience [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @roblourens @DavidKutu
- [ ] :runner: Polish general workflow experience, fix papercuts and perf issues @greazer **team**   
   - [ ] :runner: Notebook scrolling [vscode-jupyter#7360](https://github.com/microsoft/vscode-jupyter/issues/7360)
   - [x] Investigate ways to make Outline/Table of Contents more discoverable [vscode#127200](https://github.com/microsoft/vscode/issues/127200)
   - [x] Regressions from WebView or otherwise [vscode-jupyter#7361](https://github.com/microsoft/vscode-jupyter/issues/7361)
- [x] Contribute to `New File ...` [vscode-jupyter#7363](https://github.com/microsoft/vscode-jupyter/issues/7363) @IanMatthewHuff 

### Python Notebooks
- [ ] :runner: Explore intellisense dissonance between interpreters and kernels [vscode-jupyter#6333](https://github.com/microsoft/vscode-jupyter/issues/6333) @rchiodo

### Interactive Window
- [x] Polish interactive window: [vscode-jupyter#7168](https://github.com/microsoft/vscode-jupyter/issues/7168) @joyceerhl

### Documentation 
- None.

### Engineering
- [x] Separate default output renders into their own web-enabled extension [vscode-jupyter#1909](https://github.com/microsoft/vscode-jupyter/issues/1909), [vscode-jupyter#6404](https://github.com/microsoft/vscode-jupyter/issues/6404) @DonJayamanne 
- [x] Run full test pass on Codespaces (compute and no-compute) [vscode-jupyter#7592](https://github.com/microsoft/vscode-jupyter/issues/7592) @SiddhanthUnnithan  @greazer
- [ ] :runner: Update old webview tests to work against native [vscode-jupyter#6516](https://github.com/microsoft/vscode-jupyter/issues/6516), [vscode-jupyter#7028](https://github.com/microsoft/vscode-jupyter/issues/7028) @joyceerhl @rchiodo
- [ ] :runner: Simplify Code clean-up/simplification in the Jupyter extension [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950) @DonJayamanne @rchiodo @joyceerhl
- [ ] :muscle: Provide automated performance test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) @DavidKutu

### Deferred
- [ ] Placeholder kernel to ensure run button appears immediately in a notebook [vscode-jupyter#5861](https://github.com/microsoft/vscode-jupyter/issues/5861) @DonJayamanne
   - Add telemetry to get perf times for loading python & non-python kernels for the first time (without cache)
