### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#78]
* [ ] Review Extension
	* [ ] Branding (image, background etc)
	* [ ] Readme
	* [ ] Contribution guide
	* [ ] Change log

**CI**
* [ ] Update vsix names in the GitHub Workflow files
	* Currently pointing to `ms-python-insiders-nods.vsix`.
* [ ] Update Python CI pipelines to download Jupyter VSIX

**Features to validate**
* [ ] Survey links (are these correct)
* [ ] Startup Telemetry
* [ ] Telemetry (confirm it works & we get this)
* [ ] Telemetry dashboards (migrate or add new extension)
* [ ] Insiders build (this must get updated daily)
* [ ] Jupyter Output panel (display relevant info)
* [ ] Install python extension when installing this extension
* [ ] Test migration of existing user
	* [ ] Install old extension, then install new extension, validate it works without a hitch.
* [ ] Experiments
* [ ] Interactive window
	* [ ] Running cells
	* [ ] Interrupting
	* [ ] Restarting kernels
	* [ ] IPyWidgets
	* [ ] Plot viewer
	* [ ] Connecting to remote jupyter
	* [ ] Live share
* [ ] Old, custom Notebook
	* [ ] Selecting kernels
	* [ ] Running cells
	* [ ] Restarting kernels
	* [ ] Interrupting
	* [ ] IPyWidgets
	* [ ] Plot viewer
	* [ ] Connecting to remote jupyter
	* [ ] ~~Live share (this never worked before)~~
* [ ] Running extension inside docker container
	* [ ] Interactive window
	* [ ] Custom, & old notebooks
* [ ] Native notebooks (ensure this works)
* [ ] Gather
* [ ] AML Extension
* [ ] PySpark Extension
* [ ] Trusting notebooks
* [ ] Run by line
* [ ] Export to pdf, python script
* [ ] Export interactive to ipynb
* [ ] Non-Python kernels in old, custom noteooks
* [ ] Debugger in interactive window
* [ ] Variable explorer in 
	* [ ] interactive window
	* [ ] old notebook
	* [ ] custom editor
* [ ] Keyboard shortcuts for interactive window
	* [ ] We must test all (as the context keys have changed), & we have changes in Python extension
* [ ] Keyboard shorcuts for notebooks (not native)
	* [ ] We must test all (as the context keys have changed), & we have changes in Python extension
