### ISSUE TITLE
Jupyter: Iteration Plan for October 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#7874]
This plan captures our work in **October**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/134730). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

## Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment [vscode-jupyter#7876](https://github.com/microsoft/vscode-jupyter/issues/7876) **team**

### Notebooks
- Key bugs to address
  - [x] Any issue labeled [```important```](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+label%3Aimportant+milestone%3A%22October+2021%22). Typically driven through Golden Scenario runs. @greazer **team**
  - [x] Enhancements to data science survey [vscode-jupyter#6976](https://github.com/microsoft/vscode-jupyter/issues/6796) @ianmatthewhuff
  - [x] `github.dev`: All "Run" options for notebooks should lead to the "Continue Working On" prompt options [vscode#132057](https://github.com/microsoft/vscode/issues/132057) @roblourens
  - [x] Native Notebooks - Hide Jupyter contributed toolbar icons for non-jupyter kernels [vscode-jupyter#6543](https://github.com/microsoft/vscode-jupyter/issues/6543) @donjayamanne
- [ ] :runner: Improve key kernel enumeration, selection, startup, crashing, hanging issues. [vscode-jupyter#7853](https://github.com/microsoft/vscode-jupyter/issues/7853) @donjayamanne 
  - [x] Identified during investigation [vscode-jupyter#7373](https://github.com/microsoft/vscode-jupyter/issues/7373) @DonJayamanne
  - [x] Identified during investigation [vscode-jupyter#7374](https://github.com/microsoft/vscode-jupyter/issues/7374) (may be moot after fix for 7373) @DonJayamanne
- [x] Improve key intellisense scenarios for notebooks. [vscode-jupyter#7877](https://github.com/microsoft/vscode-jupyter/issues/7877) @rchiodo & **pylance team**
- [x] Improve quality and stability overall. [vscode-jupyter#7879](https://github.com/microsoft/vscode-jupyter/issues/7879) **team**

### Engineering
- [ ] :muscle: :runner: Update old webview tests to work against native [vscode-jupyter#6516](https://github.com/microsoft/vscode-jupyter/issues/6516), [vscode-jupyter#7028](https://github.com/microsoft/vscode-jupyter/issues/7028) @rchiodo
- [ ] :muscle: :runner: Simplify Code clean-up/simplification in the Jupyter extension [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950) @donjayamanne @rchiodo
- [ ] :muscle: Provide automated performance test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) **team**

### Deferred
- None.
