### ISSUE TITLE
Jupyter: Iteration Plan for November 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#8200]
This plan captures our work in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/136630). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook Focus Areas
- [ ] :runner: Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**
- [ ] :runner: Improve key kernel enumeration, selection, startup, crashing, hanging issues. [vscode-jupyter#7901](https://github.com/microsoft/vscode-jupyter/issues/7901) @donjayamanne 
  - [x] Install pip when not detected when attempting to install ipykernel [vscode-jupyter#7739](https://github.com/microsoft/vscode-jupyter/issues/7739) 
  - [x] Display warning when user selects outdated versions of Python [vscode-jupyter#7960](https://github.com/microsoft/vscode-jupyter/issues/7960)
  - [x] `!pip` not installing packages as expected [vscode-jupyter#6864](https://github.com/microsoft/vscode-jupyter/issues/6864)
  - [x] Recommend renaming python file if python file it overwrites builtins [vscode-jupyter#8195](https://github.com/microsoft/vscode-jupyter/issues/8195)
  - [x] Better handling of failed ipykernel installations & ipykernel detection [vscode-jupyter#7902](https://github.com/microsoft/vscode-jupyter/issues/7902)
  - [x] Failure to activate conda env results in failure to detect if ipykernel is installed [vscode-jupyter#8119](https://github.com/microsoft/vscode-jupyter/issues/8119)
  - [ ] :runner: Slow Kernel startup/restart [vscode-jupyter#7849](https://github.com/microsoft/vscode-jupyter/issues/7849)
- [ ] :runner: Improve key intellisense scenarios for notebooks. [vscode-jupyter#7912](https://github.com/microsoft/vscode-jupyter/issues/7912) @rchiodo & **pylance team**
  - [x] Pri 1: Modernize concat doc algorithm [vscode-jupyter#8075](https://github.com/microsoft/vscode-jupyter/issues/8075)
  - [x] Pri 1: Don't Autocomplete on '%' [vscode-jupyter#7880](https://github.com/microsoft/vscode-jupyter/issues/7880)

### Quality and Stability
- [x] Iterate / Experiment on possibilities for addressing long output workflows [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @greazer @rebornix
- [ ] :runner: [Non-blocking golden scenario issues](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+label%3Aiw-golden%2Cnb-golden+-label%3Aimportant%2Cnotebook-intellisense%2Ckernel-crash%2Ckernel-issues%2Ckernel-enumeration%2Cnotebook-kernel+is%3Aopen) @IanMatthewHuff, @amunger
- [ ] :runner: [Must-fix bug query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+milestone%3A%22November+2021%22+label%3Aregression%2C%22papercut+%3Adrop_of_blood%3A%22+-label%3Anotebook-intellisense%2Ckernel-crash%2Ckernel-issues%2Ckernel-enumeration%2Ciw-golden%2Cnb-golden+is%3Aopen) @IanMatthewHuff, @amunger, @greazer **team**
- [ ] :muscle: [Nice-to-have bug query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2021%22+-label%3Anotebook-intellisense%2Caggregate-issue%2Cenhancement%2Cengineering%2Cimportant%2Cregression%2C%2Cintellisense%2Ckernel-crash%2Cnotebook-kernel%2Ckernel-enumeration%2Ckernel-management%2Ciw-golden%2Cnb-golden+) @IanMatthewHuff, @amunger, @greazer **team**

### Engineering
- [ ] :muscle: :runner: Update old webview tests to work against native [vscode-jupyter#6516](https://github.com/microsoft/vscode-jupyter/issues/6516), [vscode-jupyter#7028](https://github.com/microsoft/vscode-jupyter/issues/7028) @rchiodo
- [ ] :muscle: :runner: Simplify Code clean-up/simplification in the Jupyter extension [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950) @donjayamanne @rchiodo
- [ ] :muscle: Provide automated performance test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) **team**

### Deferred
- None.
