### ISSUE TITLE
Jupyter: Iteration Plan for January 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#8605]
This plan captures our work in **January**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/139607). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook Focus Areas
- [x] Create NPM module to share notebook concat behavior between Jupyter and PyLance [vscode-jupyter#8467](https://github.com/microsoft/vscode-jupyter/issues/8467) @rchiodo 
- [x] Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**
- [x] [Non-blocking golden scenario bugs for January 2022 (excludes enhancements)](https://github.com/issues?q=is%3Aissue+label%3Aiw-golden%2Cnb-golden+milestone%3A%22January+2022%22+-label%3Afeature-request%2Cenhancement%2Cimportant%2Ckernel-crash%2Ckernel-issues%2Ckernel-enumeration%2Cnotebook-kernel+is%3Aopen+) @greazer **team**, @rebornix, @roblourens
- [x] [Regressions, Papercuts, and Polish for existing workflows](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2022%22+label%3Anotebook-regression%2Cnotebook-mild-regression%2C%22papercut+%3Adrop_of_blood%3A%22+-label%3Aaggregate-issue%2Cenhancement%2Cengineering%2Cimportant%2Ciw-golden%2Cnb-golden+) @greazer **team**, @rebornix, @roblourens
- [x] Move to pre-release extension model [Jupyter PR](https://github.com/microsoft/vscode-jupyter/pull/8649), [vscode#15756](https://github.com/microsoft/vscode/issues/15756) @rchiodo
- [ ] :muscle: Investigate enabling the jupyter extension as a web extension [vscode-jupyter#8664](https://github.com/microsoft/vscode-jupyter/issues/8664) @amunger

### Engineering
- [ ] :runner: Document Jupyter kernels and management architecture and code within the extension @donjayamanne @greazer **team** [vscode-jupyter-internal#241](https://github.com/microsoft/vscode-jupyter-internal/issues/241)
- [x] Document Intellisense and other extension architecture and code structure within the extension @rchiodo @greazer **team** [vscode-jupyter-internal#241](https://github.com/microsoft/vscode-jupyter-internal/issues/241)
- [ ] :muscle: :runner: Update old webview tests to work against native [vscode-jupyter#6516](https://github.com/microsoft/vscode-jupyter/issues/6516), [vscode-jupyter#7028](https://github.com/microsoft/vscode-jupyter/issues/7028) @rchiodo
- [x] Simplify Code clean-up/simplification in the Jupyter extension [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950) @donjayamanne @rchiodo
- [ ] :runner: :muscle: Provide automated performance test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) @rchiodo @greazer **team**

### Deferred (Due to key resource constraints)
- [ ] :runner: Improve key kernel enumeration, selection, startup, crashing, hanging issues. [vscode-jupyter#7901](https://github.com/microsoft/vscode-jupyter/issues/7901) @donjayamanne 
- [ ] :red_circle: :muscle: Release experimental **Scratchpad for Jupyter Notebooks** extension. @rchiodo
- [ ] :red_circle: :muscle: Release experimental **Context help for Jupyter Notebooks** extension. @rchiodo
- [ ] :muscle: [Nice-to-have bug query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2022%22+-label%3Anotebook-intellisense%2Caggregate-issue%2Cenhancement%2Cengineering%2Cimportant%2Cnotebook-regression%2C%2Cintellisense%2Ckernel-crash%2Cnotebook-kernel%2Ckernel-enumeration%2Ckernel-management%2Ciw-golden%2Cnb-golden+) @greazer **team**, @rebornix, @roblourens
