### ISSUE TITLE
Jupyter: Iteration Plan for February 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#8939]
This plan captures our work in **February**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/142359). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- [ ] :runner: Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**

### Jupyter Notebook Focus Areas
- [ ] :runner: Improve key kernel enumeration, selection, startup, crashing, hanging issues. [vscode-jupyter#7901](https://github.com/microsoft/vscode-jupyter/issues/7901) @donjayamanne 
    - [ ]  :runner: February iteration kernel issues: [Query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2022%22+label%3Akernel-enumeration%2Cnotebook-kernel%2Ckernel-crash%2Ckernel-management+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage+) @donjayamanne @greazer **team**
    - [ ] Investigate Kernel Doctor as part of above work [vscode-jupyter#5150](https://github.com/microsoft/vscode-jupyter/issues/5150) @donjayamanne @greazer **team**
- [ ] :runner: February milestone issues. Consists of key regressions, golden-scenario, and some polish.
    - [ ] :runner: [vscode-jupyter query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2022%22+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage%2Ckernel-enumeration%2Cnotebook-kernel+) @greazer **team** 
    - [ ] :runner: [vscode query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2022%22+label%3Anb-golden%2Ciw-golden+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage%2Ckernel-enumeration%2Cnotebook-kernel+) @rebornix @roblourens
- [ ] :muscle: Prep and ship preview of Jupyter "Power Tools" extension. Includes prototypes, experiments, previews of things like: **Scratchpad for Jupyter Notebooks**, **Context help for Jupyter Notebooks**, **Kernel Management** etc. @greazer **team**

### Upstream VS Code
- [x] After moving builtin renderers to be regular renderers, revisit overall default renderer packaging and installation. [vscode#142429](https://github.com/microsoft/vscode/issues/142429)

### Engineering
- [ ] :runner: Establish plan for removing package installation dependencies Jupyter has in Python (ipykernel, nbconvert, jupyter, pandas, etc). [vscode-jupyter#8457](https://github.com/microsoft/vscode-jupyter/issues/8457) @rchiodo @brettcannon
- [ ] :runner: Review & Document architecture, validate assumptions, plan improvements with discussion and help from Structure101 tool [vscode-jupyter#8933](https://github.com/microsoft/vscode-jupyter/issues/8933) @greazer **team** @rebornix @roblourens
- [ ] :muscle: Provide automated performance and test validation test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) @rchiodo and @greazer **team**
- [ ] :muscle: Review and update old webview tests to work against native [vscode-jupyter#7028](https://github.com/microsoft/vscode-jupyter/issues/7028) @rchiodo
- [ ] :muscle: Refactoring work [vscode-jupyter#6950](https://github.com/microsoft/vscode-jupyter/issues/6950) @donjayamanne @rchiodo

### Deferred
- [ ] :muscle: Investigate requirements and create plan for extension to be web-enabled. [#8664](https://github.com/microsoft/vscode-jupyter/issues/8664) Why Deferred? End to end story needs to be established as it may not be necessary to fully web-enable the Jupyter extension.
