### ISSUE TITLE
Jupyter: Iteration Plan for March 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#9245]
This plan captures our work in **March**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/144519). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- [ ] :runner: Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**

### Jupyter Notebook Focus Areas
- [ ] :runner: Core Behavior: Kernel enumeration, selection, startup, crashing, hanging issues.
    - [ ] :runner: Aggregate issue: [vscode-jupyter#7901](https://github.com/microsoft/vscode-jupyter/issues/7901) @donjayamanne
    - [ ] :runner: [March Overall Query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2022%22+label%3Akernel-enumeration%2Cnotebook-kernel%2Ckernel-crash%2Ckernel-management+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage%2Caggregate-issue+) @donjayamanne @greazer **team**
    - [ ] :runner: [Troubleshooting Wiki](https://github.com/microsoft/vscode-jupyter/wiki/Troubleshooting-(WIP)) @dojayamanne
- [ ] Core Behavior: March milestone issues. Consists of key regressions, golden-scenario, and some polish. @greazer **team**
    - [ ] :runner: [vscode-jupyter query](https://github.com/microsoft/vscode-jupyter/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2022%22+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage%2Ckernel-enumeration%2Cnotebook-kernel+) @greazer **team**
    - [ ] :runner: [vscode query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2022%22+label%3Anb-golden%2Ciw-golden+-label%3Adebt%2Citeration-plan-draft%2Cneeds-triage%2Ckernel-enumeration%2Cnotebook-kernel+) @rebornix @roblourens
- [x] :runner: Core Behavior: Move "New Jupyter Notebook" into core code [vscode-jupyter#9250](https://github.com/microsoft/vscode-jupyter/issues/9250) @amunger
- [ ] :runner: Core Behavior: Coordinate simplified getting started workflow with Python extension [vscode-jupyter#9936](https://github.com/microsoft/vscode-jupyter/issues/9336) @minsa110 @greazer
- [ ] Execution Everywhere: Investigate requirements and create plan for extension to be web-enabled. [vscode-jupyter#8664](https://github.com/microsoft/vscode-jupyter/issues/8664) @minsa110 @greazer
  - [ ] :runner: Lazy Kernels scenario definition and spike: [vscode-jupyter#9076](https://github.com/microsoft/vscode-jupyter/issues/9076) @rchiodo @rebornix @misolori
  - [ ] Gracefully handle missing kernels. [vscode-jupyter#9167](https://github.com/microsoft/vscode-jupyter/issues/9167).  @donjayamanne

### Engineering
- [ ] :runner: Prep and ship (potentially non-branded) preview of Jupyter "Power Tools" extension. Includes prototypes, experiments, previews of things like: **Scratchpad for Jupyter Notebooks**, **Context help for Jupyter Notebooks**, **Kernel Management** etc. [vscode-jupyter#9251](https://github.com/microsoft/vscode-jupyter/issues/9251) @IanMatthewHuff
- [x] Core Behavior: Move dependent package installation from Python Extension to Jupyter (ipykernel, nbconvert, jupyter, pandas, etc). [vscode-jupyter#8457](https://github.com/microsoft/vscode-jupyter/issues/8457) @rchiodo @brettcannon
- [ ] :runner: Core Behavior: Continue with review of jupyter extension architecture. Plan / Implement improvements [vscode-jupyter#8933](https://github.com/microsoft/vscode-jupyter/issues/8933) @greazer **team** @rebornix @roblourens
- [ ] :runner: Core Behavior: Provide automated performance and test validation test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437) @amunger and @greazer **team**

### Deferred
- None.
