### ISSUE TITLE
Jupyter: Iteration Plan for April 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#9566]
This plan captures our work in **April**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/146672). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

**PyCon** is at the end of the month. Looking forward to meeting some of you there!

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- [x] Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**

### Jupyter Notebook Focus Areas
- [ ] :runner: Gracefully handle connection issues with remote kernels [vscode-jupyter#9167](https://github.com/microsoft/vscode-jupyter/issues/9167) @donjayamanne
- [x] Explore remote kernel support in a web-enabled Jupyter extension [vscode-jupyter#9574](https://github.com/microsoft/vscode-jupyter/issues/9574) @rchiodo
- [x] Show kernel crash information in the output of the last run cell [vscode-jupyter#9375](https://github.com/microsoft/vscode-jupyter/issues/9375) @DonJayamanne
- [x] For avoidable kernel crashes (such as Tensorflow misconfiguration) add user guidance to the kernel crash output [vscode-jupyter#9588](https://github.com/microsoft/vscode-jupyter/issues/9588) @DonJayamanne
- [x] Continue improving wiki on kernel issues [vscode-jupyter#5291](https://github.com/microsoft/vscode-jupyter/issues/5291) @DonJayamanne
- [ ] :muscle: Explore how to improve autoselection and presentation of environments, see [vscode-jupyter#7230](https://github.com/microsoft/vscode-jupyter/issues/7230), [vscode-jupyter#9115](https://github.com/microsoft/vscode-jupyter/issues/9115), [vscode-jupyter#5998](https://github.com/microsoft/vscode-jupyter/issues/5998), [vscode-jupyter#9615](https://github.com/microsoft/vscode-jupyter/issues/9615) @DonJayamanne
- [ ] :runner: Investigate a method to create or suggest a virtual environment with `ipykernel` + needed packages for a given notebook [vscode-jupyter#9640](https://github.com/microsoft/vscode-jupyter/issues/9640) @IanMatthewHuff

### Engineering
- [x] Refactor the code base to group code with similar runtime requirements (node versus browser) [vscode-jupyter#9267](https://github.com/microsoft/vscode-jupyter/issues/9627) @rchiodo
- [ ] :runner: Stabilize test suite: identify and fix flaky tests [vscode-jupyter#9128](https://github.com/microsoft/vscode-jupyter/issues/9218) @amunger @rebornix
- [x] Assume ownership of the Interactive Window @amunger
- [x] Release the Jupyter Powertoys extension to the public, with a clear story on expectations for how features will be added / removed [vscode-jupyter#9251](https://github.com/microsoft/vscode-jupyter/issues/9251) @IanMatthewHuff
- [ ] :runner: Explore automated performance test suite [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437#issuecomment-1083700312) @amunger

### Deferred
- [ ] :runner: Mitigate slow kernel discovery (API adoption, placeholder kernels, measurements) [vscode-jupyter#9628](https://github.com/microsoft/vscode-jupyter/issues/9628) @DonJayamanne - Python extension to investigate/implement a couple of changes next iteration (#'s TBD) to make interpreter discovery much quicker for Jupyter's use case.
- [ ] Support macOS on Apple Silicon [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206) @DonJayamanne - Hardware scarcity. May need to reassign for next iteration.
