### ISSUE TITLE
Jupyter: Iteration Plan for May 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#9937]
This plan captures our work in **May**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/149008). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Jupyter Notebook High Priority
- [ ] :runner: Maintain empty list of issues labeled as an [important Golden Scenario](https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-jupyter+repo%3Amicrosoft%2Fvscode-jupyter-internal+label%3Aiw-golden%2Cnb-golden+label%3Aimportant) issue. @greazer **team**

### Jupyter Notebook Focus Areas
- [ ] :runner: Round out Lazy Kernel support to enable URI and AzML connections @donjayamanne
	- [x] Gracefully handle connection issues with remote kernels (via lazy/proxy kernels) [vscode-jupyter#9167](https://github.com/microsoft/vscode-jupyter/issues/9167)
	- [x] Support picking IJupyterServerUriInfo [vscode-jupyter#9683](https://github.com/microsoft/vscode-jupyter/issues/9683)
	- [x] :black_circle: Support multiple remote servers and related: [vscode-jupyter#9684](https://github.com/microsoft/vscode-jupyter/issues/9684)
	- [ ] :runner: :black_circle: Make connecting to remote URI's (in general) more intuitive [vscode-jupyter#9660](https://github.com/microsoft/vscode-jupyter/issues/9660)

- [ ] :runner: Fill out support for remote Jupyter server URI's in a web-enabled Jupyter extension [vscode-jupyter#9574](https://github.com/microsoft/vscode-jupyter/issues/9574) @rchiodo 
    - [x] https [vscode-jupyter#9754](https://github.com/microsoft/vscode-jupyter/issues/9754) @rchiodo
    - [x] kernel completions [vscode-jupyter#9977](https://github.com/microsoft/vscode-jupyter/issues/9977) @rchiodo
    - [ ] :runner: :muscle: intellisense full support [vscode-jupyter#9976](https://github.com/microsoft/vscode-jupyter/issues/9976) @rchiodo, **pylance team**
    - [x] notebook debugging [vscode-jupyter#9973](https://github.com/microsoft/vscode-jupyter/issues/9973) @ianmatthewhuff 
    - [ ] :runner: IW debugging [vscode-jupyter#9974](https://github.com/microsoft/vscode-jupyter/issues/9974) @donjayamanne, @ianmatthewhuff
    	- [x] Support debugging of Interactive Window using the Jupyter debugger protocol [vscode-jupyter#10037](https://github.com/microsoft/vscode-jupyter/issues/10037) @donjayamanne
    - [ ] :runner: variable window [vscode-jupyter#9664](https://github.com/microsoft/vscode-jupyter/issues/9664) @sadasant 
    - [ ] :runner: plot viewer and dataframe viewer [vscode-jupyter#9665](https://github.com/microsoft/vscode-jupyter/issues/9665) @sadasant
    - [ ] :runner: interactive window [vscode-jupyter#9717](https://github.com/microsoft/vscode-jupyter/issues/9717) @amunger, @rebornix
    - [x] export [vscode-jupyter#9996](https://github.com/microsoft/vscode-jupyter/issues/9996) @rebornix
    - [x] standard ipywidgets communications [vscode-jupyter#10051](https://github.com/microsoft/vscode-jupyter/issues/10051) @rchiodo 
    - [x] ipywidgets from CDN [vscode-jupyter#9984](https://github.com/microsoft/vscode-jupyter/issues/9984) @rchiodo
    - [ ] :muscle: File synchronization story [vscode-jupyter#9975](https://github.com/microsoft/vscode-jupyter/issues/9975) @rchiodo

- [ ] :muscle: Explore how to improve creation, autoselection and presentation of environments, see  [vscode-jupyter#9615](https://github.com/microsoft/vscode-jupyter/issues/9615), [vscode-jupyter#7230](https://github.com/microsoft/vscode-jupyter/issues/7230), [vscode-jupyter#9115](https://github.com/microsoft/vscode-jupyter/issues/9115), [vscode-jupyter#5998](https://github.com/microsoft/vscode-jupyter/issues/5998), @ianmatthewhuff
    - [ ] :muscle: Investigate a method to create or suggest a virtual environment with `ipykernel` + needed packages for a given notebook [vscode-jupyter#9640](https://github.com/microsoft/vscode-jupyter/issues/9640) @ianmatthewhuff

- [ ] IW and Notebook scrolling issues 
    - [ ] :muscle: Experiment with scrollable output regions [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @amunger
    - [x] IW doesn't scroll to bottom [vscode#145353](https://github.com/microsoft/vscode/issues/145353) @rchiodo

### Engineering
- [ ] :runner: Make use of telemetry-supported test analysis to enable a performance test [vscode-jupyter#7437](https://github.com/microsoft/vscode-jupyter/issues/7437#issuecomment-1083700312) @amunger
- [ ] Migrate off of the vscode.proposed.notebookDeprecated [vscode-jupyter#9629](https://github.com/microsoft/vscode-jupyter/issues/9629) @sadasant

### Deferred
- [ ] Support macOS on Apple Silicon [vscode-jupyter#5206](https://github.com/microsoft/vscode-jupyter/issues/5206) @donjayamanne
- [ ] Support ipywidgets without a CDN [vscode-jupyter#10060](https://github.com/microsoft/vscode-jupyter/issues/10060) @rchiodo
